### ISSUE TITLE
160GB of launchd-stderr.log

### ISSUE THREAD

**Issue by TimonB** [containers/podman-desktop#10120]
### Bug description

On my Macbook (M1) I was running out of space. Suddenly "no space left on device". I have identified the logfiles from podman desktop as problem:

```
160G 26 Nov 17:15 launchd-stderr.log
1,7G 20 Nov 23:30 launchd-stdout.log
```

Last lines of the logfile are

```
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I don't know what went wrong here. I didn't notice any problems with podman desktop. I would expect that logfiles should never get so huge

### Operating system

macOs 15.1.1

### Installation Method

Installer from website/GitHub releases

### Version

1.14.1

### Relevant log output

```shell

```

**Comment by odockal** [comment]
Relates to: https://github.com/podman-desktop/podman-desktop/issues/9577

**Comment by jeffmaury** [comment]
> Relates to: [#10120](https://github.com/podman-desktop/podman-desktop/issues/10120)

This is a self reference

**Comment by odockal** [comment]
> > Relates to: [#10120]
> 
> This is a self reference

Sry! Fixed now.

**Comment by devdilson** [comment]
Had the same issue today.

**Comment by odockal** [comment]
There is a way to achieve the log cleanup/truncation without need to logout or restart:
Have Podman Desktop 1.16.1 running and do:
```
launchctl unload  ~/Library/LaunchAgents/io.podman_desktop.PodmanDesktop.plist
launchctl load  ~/Library/LaunchAgents/io.podman_desktop.PodmanDesktop.plist
```

**Comment by benoitf** [comment]
https://podman-desktop.io/docs/troubleshooting/troubleshooting-podman-on-macos#running-out-of-disk-space-on-macos
