### ISSUE TITLE
Dashboard stuck at "Loading extensions..."

### ISSUE THREAD

**Issue by lazar-boradzhiev** [containers/podman-desktop#10171]
### Bug description

I was very happy with my Podman dashboard installation for a couple of weeks already until yesterday when I started the dashboard as usual, but it would not open. Right clicking the tray icon would not show anything and the processes in task manager would appear stuck 

![Image](https://github.com/user-attachments/assets/8abdfa00-0a96-4631-b250-4378bbe8998f)

Starting the dashboard from the CLI yields the following logs:

```bash
$ ./"Podman Desktop.exe"

Installing Podman Desktop startup file at C:\Users\{redacted}\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\podman-desktop.vbs using C:\Users\{redacted}\AppData\local\Programs\podman-desktop\Podman Desktop.exe location.
Error while getting Windows internet settings from registry vl: QUERY command exited with code 1:

ERROR: Registry editing has been disabled by your administrator.
    at hc (C:\Users\{redacted}\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:335:21)
    at ChildProcess.<anonymous> (C:\Users\{redacted}\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:335:2147)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: [Getter]
}
Checking for update
Starting http server to handle webviews on port 44000
System ready. Loading extensions...

```

The "ERROR: Registry editing has been disabled by your administrator." is also observed by peers, but the dashboard would still start normally for them.

**Things I tried:**
* Restarting the PC.
* Uninstalling, manually cleaning all podman desktop directories and reinstalling it.
* Starting as administrator.

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.14.1

### Steps to reproduce

1. Clean old podman-desktop installations.
2. Install latest (1.14.1) podman-desktop from website.

### Relevant log output

```shell

```

**Comment by ScrewTSW** [comment]
@lazar-boradzhiev Hello. Is it possible registry editing is disallowed by your company's group policy?
It might have been a recent change, there's a chance your co-workers might hit the same issue upon cleanup and reinstall.

**Comment by lazar-boradzhiev** [comment]
> @lazar-boradzhiev Hello. Is it possible registry editing is disallowed by your company's group policy?
> It might have been a recent change, there's a chance your co-workers might hit the same issue upon cleanup and reinstall.

Hi @ScrewTSW l. Thank you for looking into this. The policy is not new and it has been active for atleast a couple of months. My peers are experiencing the same registry error, but their dashboard still starts and operates normally.

**Comment by gastoner** [comment]
@lazar-boradzhiev does this issue persist with the 1.15 release?

**Comment by lazar-boradzhiev** [comment]
> @lazar-boradzhiev does this issue persist with the 1.15 release? 

Hello, after installing the 1.15 the dashboard now starts and operates back to normal. Thank you!

**Comment by gastoner** [comment]
Closing this, since it was a 1.14.1 issue and it is not present in 1.15
