### ISSUE TITLE
Kubernetes Port Forwarding always fails with "Host is not reachable"

### ISSUE THREAD

**Issue by stkr22** [containers/podman-desktop#10476]
### Bug description

Installed Podman Desktop via flatpak and tried the port forwarding feature but it never works. It always shows "Error: Host is not reachable: This operation was aborted".

![Image](https://github.com/user-attachments/assets/cb4bc503-e9f5-41ca-87a7-db2633917cfc)

Port forwarding using kubectl or VSCode works fine and without any issues.

### Operating system

Ubuntu 24.04

### Installation Method

Flathub (Linux)

### Version

1.15.0

### Steps to reproduce

1. Start a pod in kubernetes
2. Go to "Pod Details"
3. Click on Summary > "Forward..." 

### Relevant log output

```shell

```

**Comment by odockal** [comment]
Errors that appear in console log for me when I encounter the same error. (1.16.0-next) installed from flatpak:
```
main ↪️ (node:3) UnhandledPromiseRejectionWarning: TypeError: xW is not a constructor
    at /app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:204:1133258
    at new Promise (<anonymous>)
    at sn.connect (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:204:1133184)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sn.processData (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:204:1132432)
    at async /app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:204:1132686

main ↪️ (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 29)
console.<computed> @ VM270:2
(anonymous) @ VM270:2
emit @ VM269 sandbox_bundle:2
onMessage @ VM269 sandbox_bundle:2

Error: Host is not reachable: This operation was aborted
  | o | @ | KubePort.svelte:46
-- | -- | -- | --
  | await in o |   |  
  | click | @ | KubePort.svelte:99
  | (anonymous) | @ | Button.svelte:76
```

**Comment by odockal** [comment]
@feloy Just a side note, the scenario fails on all OSes now. I am quite confident that it worked last release. I will try to find out more what change broke it.

**Comment by feloy** [comment]
I can see on the line https://github.com/podman-desktop/podman-desktop/blob/main/packages/main/src/plugin/kubernetes/kubernetes-port-forward-connection.ts#L135 that `fetch` is used to check port connectivity. For this reason, only HTTP-like connections can be tested, and here, because we try to forward a PostgreSQL connection, which is not HTTP-based, this fails.

**Comment by odockal** [comment]
So we opened a new issue, which is related to this: https://github.com/podman-desktop/podman-desktop/issues/10844

**Comment by feloy** [comment]
Fixed by #10877
