### ISSUE TITLE
Hitting Ctrl+R Breaks `podman container list`

### ISSUE THREAD

**Issue by RobotSail** [containers/podman-desktop#1123]
### Bug description

When you launch podman desktop and hit `ctrl+r` to reload the application's data, it breaks the response times from `podman`. This issue affects the actual podman binary, not just the API within Podman desktop.

For example:
```shell
➜  podman-desktop git:(main) ✗ time podman container list --all
CONTAINER ID  IMAGE                                          COMMAND          CREATED             STATUS            PORTS                   NAMES
eaa96b9e0485  quay.io/fetchit/fetchit:latest                 entry.sh         5 minutes ago       Up 5 minutes ago                          podman-desktop-fetchit
66d9ba35ad74  docker.io/mmumshad/simple-webapp-color:latest  python ./app.py  4 minutes ago       Created           0.0.0.0:8080->8080/tcp  colors1
d0e2e1ce9152  docker.io/mmumshad/simple-webapp-color:latest  python ./app.py  2 minutes ago       Created           0.0.0.0:9090->8080/tcp  cap2
22ec51dcec0c  docker.io/mmumshad/simple-webapp-color:latest  python ./app.py  About a minute ago  Created           0.0.0.0:9080->8080/tcp  colors2
podman container list --all  0.04s user 0.03s system 0% cpu 38.756 total
```

Podman version:
```
➜  ~ podman version
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.4
Built:        Wed Dec 31 19:00:00 1969
OS/Arch:      linux/amd64
```

### Operating system

Ubuntu 22.04.1 LTS

### Version

next (development version)

### Steps to reproduce

Open Podman Desktop (latest build) and press `ctrl+R`

### Relevant log output

```shell
I'm unsure if this log is relevant to the issue at all, but this was printed during the timespan of the issue happening:


4:50:48 PM [main] (node:1951387) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 217)
4:53:10 PM [main] (node:1951387) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, watch '/var/run/systemd/sessions/96.ref'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2301:34)
    at createFsWatchInstance (/home/oleg/Programming/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/oleg/Programming/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/oleg/Programming/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/home/oleg/Programming/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:395:23)
```
```


### Additional context

This issue is happening on a development build of Podman desktop on Ubuntu.
The problem might also be the specific podman version being used, as I had to go through some extra effort to get Podman version 4.3 on Ubuntu, since the one included in the default repos is 3.x. 

I also didn't get this issue on my main system (MacOS 13, Apple M1).

**Comment by RobotSail** [comment]
Not sure if this is related to the original issue or not, but now podman desktop is stuck on "Initializing" whenever I try launching the latest build via `yarn watch`.

**Comment by benoitf** [comment]
@RobotSail https://github.com/containers/podman-desktop/issues/951 ?

**Comment by benoitf** [comment]
I suggest to look at the developer console, you should probably have an error being reported

**Comment by RobotSail** [comment]
It may be related to #951, but my problem happened over on Linux and the console is complaining about EACCESS to `/var/log/systemd/journal` as well as too many symbolic links:

```
(node:2568237) UnhandledPromiseRejectionWarning: Error: ELOOP: too many symbolic links encountered, stat '/var/run/udev/watch/17'
(node:2568237) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 212)
(node:2568237) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, watch '/var/run/user/1000/systemd/inaccessible/dir'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2301:34)
    at createFsWatchInstance (/home/oleg/Programming/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/oleg/Programming/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/oleg/Programming/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleDir (/home/oleg/Programming/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:567:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Looking at the dev console, it seems that the first error is lima being unable to find a Podman socket:
```
main ↪️ [lima] Could not find podman socket at /home/oleg/.lima/podman-lima/sock/podman.sock nor /home/oleg/.lima/podman-lima/sock/podman.sock
```

Following that, the first error in a long line of similar errors appears to be an EACCESS on `/var/run/apport.lock`:
```
main ↪️ (node:2580527) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, watch '/var/run/apport.lock'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2301:34)
    at createFsWatchInstance (/home/oleg/Programming/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/oleg/Programming/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/oleg/Programming/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/home/oleg/Programming/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/home/oleg/Programming/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:637:21)
(Use `electron --trace-warnings ...` to show where the warning was created)
(anonymous) @ index.ts:119
```

I've also tried to enable debug level logging within the `scripts/watch.cjs` file, but I'm not sure how I can enable `--trace-warnings` when running via `yarn watch`, I guess there's more reading for me to do.

**Comment by RobotSail** [comment]
So the above problem of podman desktop being stuck on initializing was to do with permissions settings within a VNC environment, I was able to solve it by running `xhost +` within a terminal on the display side. The original problem of `podman container list` after hitting Ctrl+R still exists, however.

**Comment by benoitf** [comment]
@RobotSail I think it's due to the lock of the Podman REST API.

You may grab the locks using `kill -SIGABRT` on podman process
