### ISSUE TITLE
Infinite loop when watching "/var/run"

### ISSUE THREAD

**Issue by orblazer** [containers/podman-desktop#1435]
### Bug description

The new feature `Docker compatibility mode` from #1047 introduce infinite loop on all process and that freeze the computer.

### Operating system

Linux 5.15.91-1-MANJARO

### Version

0.11.0

### Steps to reproduce

Simply start the application without have docker compatibility.

### Relevant log output

```shell
Gtk-Message: 16:06:30.186: Failed to load module "appmenu-gtk-module"
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
Activating extension (crc)
[crc] Can not find CRC binary!
Activation extension (crc) ended
Activating extension (docker)
Activation extension (docker) ended
Activating extension (kube-context)
[kube-context] starting extension kube-context
Activation extension (kube-context) ended
Activating extension (lima)
[lima] Could not find podman socket at /home/orblazer/.lima/podman-lima/sock/podman.sock nor /home/orblazer/.lima/podman-lima/sock/podman.sock
Activation extension (lima) ended
Activating extension (podman)
Activating extension (registries)
Activation extension (registries) ended
[podman] Error while pinging docker as podman Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
(node:43452) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, watch '/var/run/dmeventd-client'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2301:34)
    at createFsWatchInstance (/opt/podman-desktop-bin/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/opt/podman-desktop-bin/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/opt/podman-desktop-bin/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/opt/podman-desktop-bin/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/opt/podman-desktop-bin/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
(Use `podman-desktop --trace-warnings ...` to show where the warning was created)
(node:43452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

The last error loop with all process.

### Additional context

- I run podman in rootless.
- This issue come from https://github.com/containers/podman-desktop/blob/c34ea0bb47226e7e50a45a0f17396bbda451b2a6/extensions/podman/src/extension.ts#L596

**Comment by benoitf** [comment]
@orblazer are you using flatpak or the linux binary ?

**Comment by orblazer** [comment]
hello @benoitf, i have installed the packages from official repo for `podman` and `podman-compose` and directly from AUR for `podman-desktop-bin`, so no flatpak.

But i have the same issue with latest version (when i run from source).
