### ISSUE TITLE
Creating Kind cluster fails if previous cluster running

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2044]
### Bug description

If you have an existing Kind cluster running and then try to create a new one, it completes a bit faster than normal and says it was successful, but no container/cluster is actually created.

### Operating system

macOS 13.3 M1

### Version

next (development version)

### Steps to reproduce

Create a Kind cluster and leave it running, then try to create a second one.

### Relevant log output

```shell
There is a lot of output so it's hard to scan for errors, but the last one was this:
9:41:40 a.m. [main] error in engine Podman Error: (HTTP code 500) server error - failed to get state of container b55c10b0bbf8e96e47ca32bea81d0938d39201ca4b17fb4954170296a03bd03e: container b55c10b0bbf8e96e47ca32bea81d0938d39201ca4b17fb4954170296a03bd03e does not exist in database: no such container 
    at /Users/deboer/git/alternates/podman-desktop-alt/packages/main/dist/index.cjs:17266:18
    at getCause (/Users/deboer/git/alternates/podman-desktop-alt/packages/main/dist/index.cjs:17293:7)
    at Modem$1.buildPayload (/Users/deboer/git/alternates/podman-desktop-alt/packages/main/dist/index.cjs:17265:5)
    at IncomingMessage.<anonymous> (/Users/deboer/git/alternates/podman-desktop-alt/packages/main/dist/index.cjs:17241:15)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  reason: 'server error',
  statusCode: 500,
  json: {
    cause: 'no such container',
    message: 'failed to get state of container b55c10b0bbf8e96e47ca32bea81d0938d39201ca4b17fb4954170296a03bd03e: container b55c10b0bbf8e96e47ca32bea81d0938d39201ca4b17fb4954170296a03bd03e does not exist in database: no such container',
    response: 500
  }
}
```

### Additional context

Ideally it would be good if we can create the second cluster while the first is running. If the first one needs to be stopped in order to do it, prompting the user with an appropriate error or getting their approval to stop the other cluster would be fine too.

**Comment by benoitf** [comment]
it's a dup of https://github.com/containers/podman-desktop/issues/2029
you have an error thrown
