### ISSUE TITLE
Network Error on the UI

### ISSUE THREAD

**Issue by renatoppuccini** [containers/podman-desktop#2046]
### Bug description

After sometime running and laptop closed/disconnected from wifi and connected again, an error message pops up from Podman-desktop

### Operating system

MacOs Monterey Version 12.6.3

### Version

0.13.0

### Steps to reproduce

1. Turn on Podman and Podman-desktop
2. Enable the docker socket to run docker-compose
3.  Start containers
4. Podify them
5. Leave them running
6. After sometime the error pops up

<img width="260" alt="image" src="https://user-images.githubusercontent.com/1215178/231495582-e165ae3a-6d18-4687-805f-74f04d81cb3f.png">

**Comment by benoitf** [comment]
thanks for the report. I suppose that it's the self-update that is not able to grab data remotely and then it displays some error
ERR_NETWORK_CHANGED should be skipped and not displayed to the user

**Comment by renatoppuccini** [comment]
is that trying to get information from my Kubeconfig ?
it has a url from a previous deleted demo openshift cluster.


index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
index.ts:1224 main ↪️ error in engine Podman Error: (HTTP code 500) server error - failed to get state of container 1b370388bb7d060ead7f996eb6d2afab06bbbb066dae921d2c30aa6e8cbd95f7: container 1b370388bb7d060ead7f996eb6d2afab06bbbb066dae921d2c30aa6e8cbd95f7 does not exist in database: no such container 
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5555
    at c (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5886)
    at As.buildPayload (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5527)
    at IncomingMessage.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5077)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
index.ts:1224 main ↪️ error in engine Podman Error: (HTTP code 500) server error - failed to get state of container 33c1aca26dd0e2b708ea7fe47cf0c5f72a7c6bf47124cea7fb39d1a224576eb2: container 33c1aca26dd0e2b708ea7fe47cf0c5f72a7c6bf47124cea7fb39d1a224576eb2 does not exist in database: no such container 
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5555
    at c (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5886)
    at As.buildPayload (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5527)
    at IncomingMessage.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5077)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
index.ts:1224 main ↪️ error in engine Podman Error: (HTTP code 500) server error - failed to get state of container 33c1aca26dd0e2b708ea7fe47cf0c5f72a7c6bf47124cea7fb39d1a224576eb2: container 33c1aca26dd0e2b708ea7fe47cf0c5f72a7c6bf47124cea7fb39d1a224576eb2 does not exist in database: no such container 
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5555
    at c (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5886)
    at As.buildPayload (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5527)
    at IncomingMessage.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5077)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ error in engine Podman Error: (HTTP code 500) server error - failed to get state of container 6a9802b92cbeee21ad4c7495afa98c8a60cc31f5c075c91dfc89447c3e494970: container 6a9802b92cbeee21ad4c7495afa98c8a60cc31f5c075c91dfc89447c3e494970 does not exist in database: no such container 
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5555
    at c (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5886)
    at As.buildPayload (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5527)
    at IncomingMessage.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5077)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
index.ts:1224 main ↪️ error in engine Podman Error: (HTTP code 500) server error - failed to get state of container 6a9802b92cbeee21ad4c7495afa98c8a60cc31f5c075c91dfc89447c3e494970: container 6a9802b92cbeee21ad4c7495afa98c8a60cc31f5c075c91dfc89447c3e494970 does not exist in database: no such container 
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5555
    at c (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5886)
    at As.buildPayload (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5527)
    at IncomingMessage.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5077)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
index.ts:1224 main ↪️ error in engine Podman Error: (HTTP code 500) server error - failed to get state of container 6a9802b92cbeee21ad4c7495afa98c8a60cc31f5c075c91dfc89447c3e494970: container 6a9802b92cbeee21ad4c7495afa98c8a60cc31f5c075c91dfc89447c3e494970 does not exist in database: no such container 
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5555
    at c (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5886)
    at As.buildPayload (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5527)
    at IncomingMessage.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:7:5077)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
index.ts:1224 main ↪️ event is Object
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
pods.ts:31 Uncaught (in promise) Error: getaddrinfo ENOTFOUND api.lpl.sandbox465.opentlc.com
index.ts:1224 main ↪️ Error: Error: net::ERR_NETWORK_CHANGED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49386)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
(anonymous) @ index.ts:1224
index.ts:1224 main ↪️ unable to check for updates Error: net::ERR_NETWORK_CHANGED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49386)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
(anonymous) @ index.ts:1224
index.ts:1224 main ↪️ unable to check for updates Error: net::ERR_NETWORK_CHANGED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49386)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)

**Comment by benoitf** [comment]
It reads the kubeconfig to display the pods in the Pods section
And it reads the kubeconfig file to display the kube context in the tray icon
