### ISSUE TITLE
Running the PD in watch mode shows some unhandled promise rejection warning about "too many open files" on Linux

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2054]
### Bug description

When I run Podman Desktop from main branch in watch mode I got to see quite a lot unhandled promise rejections. This snippet is just from a app. startup.

### Operating system

Fedora 37

### Version

next (development version)

### Steps to reproduce

1. yarn install
2. yarn watch

### Relevant log output

```shell
build started...
✓ 1196 modules transformed.
dist/index.cjs  10,215.81 kB │ map: 5,550.43 kB
built in 7409ms.
9:26:38 PM [main] (electron:44609): Gtk-WARNING **: 21:26:38.757: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(electron:44609): Gtk-WARNING **: 21:26:38.757: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
9:26:38 PM [main] [44609:0412/212638.802810:ERROR:socket_posix.cc(147)] bind() failed: Address already in use (98)
9:26:38 PM [main] [44609:0412/212638.802854:ERROR:devtools_http_handler.cc(312)] Cannot start http server for devtools.
9:26:38 PM [main] [44644:0412/212638.859552:ERROR:file_path_watcher_inotify.cc(315)] inotify_init() failed: Too many open files (24)
9:26:38 PM [main] libva error: /usr/lib64/dri/i965_drv_video.so init failed
9:26:38 PM [main] (node:44609) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/home/odockal/.kube/config'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2315:34)
    at createFsWatchInstance (/home/odockal/git/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/odockal/git/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/odockal/git/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/home/odockal/git/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/home/odockal/git/podman-desktop/node_modules/chokidar/lib/nodefs-handler.js:637:21)
    at async /home/odockal/git/podman-desktop/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:44609) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
9:26:39 PM [main] System ready. Loading extensions...

9:26:39 PM [main] (node:44609) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/home/odockal/.local/share/containers/podman-desktop/plugins-scanning'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Module.watch (node:fs:2315:34)
    at ExtensionLoader.setupScanningDirectory (/home/odockal/git/podman-desktop/packages/main/dist/index.cjs:37808:21)
    at ExtensionLoader.start (/home/odockal/git/podman-desktop/packages/main/dist/index.cjs:37818:16)
    at PluginSystem.initExtensions (/home/odockal/git/podman-desktop/packages/main/dist/index.cjs:91936:32)
    at async /home/odockal/git/podman-desktop/packages/main/dist/index.cjs:92131:29
(node:44609) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```
...
```
9:26:41 PM [vite-plugin-svelte] /src/lib/pod/DeployPodToKube.svelte:339:20 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
9:26:42 PM [main] (node:44609) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
(node:44609) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
9:26:43 PM [vite-plugin-svelte] /src/lib/statusbar/StatusBarItem.svelte:34:0 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
9:26:43 PM [vite-plugin-svelte] /src/lib/image/ImageActions.svelte:94:4 A11y: noninteractive element cannot have nonnegative tabIndex value
9:26:43 PM [vite-plugin-svelte] /src/lib/image/PushImageModal.svelte:97:2 A11y: noninteractive element cannot have nonnegative tabIndex value
9:26:44 PM [vite-plugin-svelte] /src/lib/dialogs/Modal.svelte:63:0 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
9:26:44 PM [vite-plugin-svelte] /src/lib/dialogs/Modal.svelte:25:0 Unused CSS selector "button"
9:26:44 PM [vite-plugin-svelte] /src/lib/dashboard/ProviderLinks.svelte:7:6 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
9:26:47 PM [main] PluginSystem: received dom-ready event from the UI

9:26:47 PM [main] Delayed startup, flushing 8 events

9:26:50 PM [main] (node:44609) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
9:26:50 PM [main] (node:44609) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
```

**Comment by benoitf** [comment]
@odockal maybe you could raise your limit if there is one for open files ?
watch mode is watching a lot of files

**Comment by odockal** [comment]
@benoitf Yeah, that works.

**Comment by odockal** [comment]
Maybe to put this somewhere in contributing guide.

**Comment by veillard** [comment]
It is still weird that Podman Desktop raises this but for example Nautilus the file browser which also need to monitor for many file changes doesn't. Maybe the code ends up watching over and over the same directory or something similar. inotify is the linux kernel interface to watch individual files changes. One stategy I remember from when I was working on gamin (a FAM API implementation) is that you can watch the directory instead of all the individual files for changes.

**Comment by benoitf** [comment]
closing as won't fix
it relies on the system (and also javascript libraries are using ton of small files)
