### ISSUE TITLE
Unable to install Podman (4.4.4-setup.exe not found) on Windows 10

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#2102]
### Bug description

On a fresh system with no Podman installed, I'm unable to install Podman and it fails with 4.4.4-setup.exe not found.

https://user-images.githubusercontent.com/6422176/232052383-d938b3c4-adaf-42aa-bc95-f54b4eb6929e.mov

### Operating system

Windows 10 Enterprise

### Version

0.14.0

### Steps to reproduce

1. No Podman installed
2. Compile (not yarn watch) Podman Desktop binary
3. Try to install Podman

### Relevant log output
```
Can't find Podman setup package! Path: C:\Users\admin\AppData\Local\Temp\2OPzvz5i1hyqqrwvdJ0Bkv9ACAB\resources\extensions\podman\assets\podman-4.4.4-setup.exe doesn't exists.
    at C:\Users\admin\AppData\Local\Temp\2OPzvz5i1hyqqrwvdJ0Bkv9ACAB\resources\app\extensions\podman\builtin\podman.cdix\dist\extension.js:819:27
    at uU.withProgress (C:\Users\admin\AppData\Local\Temp\2OPzvz5i1hyqqrwvdJ0Bkv9ACAB\resources\app\packages\main\dist\index.cjs:83:19109)
    at Object.withProgress (C:\Users\admin\AppData\Local\Temp\2OPzvz5i1hyqqrwvdJ0Bkv9ACAB\resources\app\packages\main\dist\index.cjs:83:30619)
    at WinInstaller.install (C:\Users\admin\AppData\Local\Temp\2OPzvz5i1hyqqrwvdJ0Bkv9ACAB\resources\app\extensions\podman\builtin\podman.cdix\dist\extension.js:805:47)
    at PodmanInstall.installBundledPodman (C:\Users\admin\AppData\Local\Temp\2OPzvz5i1hyqqrwvdJ0Bkv9ACAB\resources\app\extensions\podman\builtin\podman.cdix\dist\extension.js:760:30)
    at PodmanInstall.doInstallPodman (C:\Users\admin\AppData\Local\Temp\2OPzvz5i1hyqqrwvdJ0Bkv9ACAB\resources\app\extensions\podman\builtin\podman.cdix\dist\extension.js:689:24)
    at async C:\Users\admin\AppData\Local\Temp\2OPzvz5i1hyqqrwvdJ0Bkv9ACAB\resources\app\packages\main\dist\index.cjs:333:1606
    at async node:electron/js2c/browser_init:2:97945
(
```

**Comment by cdrage** [comment]
Closing: Issue is you cannot build the exe from another machine (linux or mac) and transfer over + run it. Must be built on Windows to test.
