### ISSUE TITLE
Make contour file offline: Download contour on tests making CI fail / exceed our rate limits.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#2248]
### Bug description

See: https://github.com/containers/podman-desktop/actions/runs/4809808101/jobs/8561561825?pr=2149

We should be storing our contour.yaml file offline / packaged within podman desktop as we are hitting our CI limits for tests.

This also blocks any future releases as flatpak bundling is created offline. 

### Operating system

M1

### Version

0.14.1

### Relevant log output

```shell
> kind@0.0.1 build
> npx ts-node ./scripts/download.ts && vite build && node ./scripts/build.js

Downloading Contour manifests from https://github.com/projectcontour/contour/examples/render/contour.yaml version v1.24.2
Request quota exhausted for request GET /repos/{owner}/{repo}/contents/{path}
Request quota exhausted for request GET /repos/{owner}/{repo}/contents/{path}
RequestError [HttpError]: API rate limit exceeded for 168.61.76.113. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at /home/runner/work/podman-desktop/podman-desktop/node_modules/@octokit/request/dist-src/fetch-wrapper.js:70:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Job.doExecute (/home/runner/work/podman-desktop/podman-desktop/node_modules/bottleneck/light.js:405:18) {
  status: 403,
  response: {
```
```


### Additional context

_No response_

**Comment by benoitf** [comment]
probably a dup/merge/sub-issue of https://github.com/containers/podman-desktop/issues/2111

**Comment by cdrage** [comment]
> probably a dup/merge/sub-issue of #2111

Sorta! I opened this in case people encounter the error from CI.
