### ISSUE TITLE
Flaky test in e2e.spec.ts

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2312]
### Bug description

We have a flaky test, which causes many PR tests to fail the `pr-check / linter, formatters and unit tests` action. We should fix this to reduce the number of failed runs, avoid having to rerun this action, and be able to release PRs easier.

### Operating system

macOS 13.3 M1

### Version

next (development version)

### Relevant log output

```shell
RUN  v0.30.1 /home/runner/work/podman-desktop/podman-desktop

 ❯ tests/e2e.spec.ts  (2 tests | 1 failed) 2981ms
   ❯ tests/e2e.spec.ts > Main window state
     → electronApplication.evaluate: TypeError: Cannot read properties of undefined (reading 'isVisible')
    at eval (eval at evaluate (:197:30), <anonymous>:9:24)
    at new Promise (<anonymous>)
    at eval (eval at evaluate (:197:30), <anonymous>:8:14)
    at UtilityScript.evaluate (<anonymous>:199:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at _._init (node:electron/js2c/browser_init:2:80038)
    at createWindow (/home/runner/work/podman-desktop/podman-desktop/packages/main/dist/index.cjs:13042:25)
    at createNewWindow (/home/runner/work/podman-desktop/podman-desktop/packages/main/dist/index.cjs:13149:21)
    at /home/runner/work/podman-desktop/podman-desktop/packages/main/dist/index.cjs:104150:5

⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  tests/e2e.spec.ts > Main window state
Error: electronApplication.evaluate: TypeError: Cannot read properties of undefined (reading 'isVisible')
    at eval (eval at evaluate (:197:30), <anonymous>:9:24)
    at new Promise (<anonymous>)
    at eval (eval at evaluate (:197:30), <anonymous>:8:14)
    at UtilityScript.evaluate (<anonymous>:199:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at _._init (node:electron/js2c/browser_init:2:80038)
    at createWindow (/home/runner/work/podman-desktop/podman-desktop/packages/main/dist/index.cjs:13042:25)
    at createNewWindow (/home/runner/work/podman-desktop/podman-desktop/packages/main/dist/index.cjs:13149:21)
    at /home/runner/work/podman-desktop/podman-desktop/packages/main/dist/index.cjs:104150:5
 ❯ _._init node:electron/js2c/browser_init:2:80038
 ❯ tests/e2e.spec.ts:16:112
     14| 
     15| test('Main window state', async () => {
     16|   const windowState: { isVisible: boolean; isDevToolsOpened: boolean; …
       |                                                                                                                ^
     17|     ({ BrowserWindow }) => {
     18|       const mainWindow = BrowserWindow.getAllWindows()[0];

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  1 failed | 1 passed (2)
```

**Comment by benoitf** [comment]
It's related/dup of https://github.com/containers/podman-desktop/issues/1780
