### ISSUE TITLE
Errors in the log occured when starting an OpenShift local (OpenShift preset) - no obvious issue

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2518]
### Bug description

I was starting a stopped openshift local cluster via podman desktop and spotted in the console log errors during startup. No real issue, though.

### Operating system

Fedora 37

### Version

next (development version)

### Relevant log output

```shell
(anonymous) @ main.ts:3
index.ts:1327 main ↪️ [kind] kind extension is active
index.ts:1327 main ↪️ [openshift-local] Error: cluster is busy

    at DaemonCommander.start (/home/odockal/.local/share/containers/podman-desktop/plugins/ghcriocrcorgcrcextension/dist/extension.js:9345:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startCrc (/home/odockal/.local/share/containers/podman-desktop/plugins/ghcriocrcorgcrcextension/dist/extension.js:25275:24)
    at async Object.start (/home/odockal/.local/share/containers/podman-desktop/plugins/ghcriocrcorgcrcextension/dist/extension.js:26388:13)
    at async zj.startProviderLifecycle (/home/odockal/git/podman-desktop/dist/linux-unpacked/resources/app/packages/main/dist/index.cjs:83:49353)
    at async /home/odockal/git/podman-desktop/dist/linux-unpacked/resources/app/packages/main/dist/index.cjs:335:16935
    at async node:electron/js2c/browser_init:2:97971
(anonymous) @ index.ts:1327
emit @ VM123 sandbox_bundle:2
onMessage @ VM123 sandbox_bundle:2
index.ts:1327 main ↪️ [kind] kind extension is active
index.ts:1327 main ↪️ Kube event error Error: aborted
    at connResetException (node:internal/errors:717:14)
    at TLSSocket.socketCloseListener (node:_http_client:462:19)
    at TLSSocket.emit (node:events:525:35)
    at node:net:322:12
    at TCP.done (node:_tls_wrap:588:7)
(anonymous) @ index.ts:1327
emit @ VM123 sandbox_bundle:2
onMessage @ VM123 sandbox_bundle:2
```
```


### Additional context

_No response_

**Comment by benoitf** [comment]
openshift local extension issue should be reported to https://github.com/crc-org/crc-extension
