### ISSUE TITLE
error when ~/.kube/config goes to /dev/null

### ISSUE THREAD

**Issue by chmouel** [containers/podman-desktop#2683]
### Bug description

For different reasons (i use different kubeconfig) i have my ~/.kube/config pointing to /dev/null

when i run podman-desktop i get an error:

```
An error happened when loading kubeconfig file at /home/chmouel/.kube/config TypeError: Cannot read properties of undefined (reading 'clusters')
    at KubeConfig.loadFromString (/opt/podman-desktop-bin/resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:115:61)
    at KubeConfig.loadFromFile (/opt/podman-desktop-bin/resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:76:14)
    at QI.refresh (/opt/podman-desktop-bin/resources/app.asar/packages/main/dist/index.cjs:250:5540)
    at /opt/podman-desktop-bin/resources/app.asar/packages/main/dist/index.cjs:250:3596
    at /opt/podman-desktop-bin/resources/app.asar/packages/main/dist/index.cjs:40:4819
    at TH.invoke (/opt/podman-desktop-bin/resources/app.asar/packages/main/dist/index.cjs:40:4923)
    at ot.fire (/opt/podman-desktop-bin/resources/app.asar/packages/main/dist/index.cjs:42:293)
    at FSWatcher.<anonymous> (/opt/podman-desktop-bin/resources/app.asar/packages/main/dist/index.cjs:251:8132)
    at FSWatcher.emit (node:events:513:28)
    at FSWatcher.emitWithAll (/opt/podman-desktop-bin/resources/app.asar/node_modules/chokidar/index.js:540:8)
PluginSystem: received dom-ready event from the UI
Delayed startup, flushing 28 events
[kind] kind extension is active
[kind] kind extension is active
Activation extension (podman) ended
PluginSystem: initialization done.
Autostarting container engine
An error happened when loading kubeconfig file at /home/chmouel/.kube/config TypeError: Cannot read properties of undefined (reading 'clusters')
    at KubeConfig.loadFromString (/opt/podman-desktop-bin/resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:115:61)
    at KubeConfig.loadFromFile (/opt/podman-desktop-bin/resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:76:14)
    at QI.refresh (/opt/podman-desktop-bin/resources/app.asar/packages/main/dist/index.cjs:250:5540)
    at /opt/podman-desktop-bin/resources/app.asar/packages/main/dist/index.cjs:250:3596
    at /opt/podman-desktop-bin/resources/app.asar/packages/main/dist/index.cjs:40:4819
    at TH.invoke (/opt/podman-desktop-bin/resources/app.asar/packages/main/dist/index.cjs:40:4923)
    at ot.fire (/opt/podman-desktop-bin/resources/app.asar/packages/main/dist/index.cjs:42:293)
    at FSWatcher.<anonymous> (/opt/podman-desktop-bin/resources/app.asar/packages/main/dist/index.cjs:251:8132)
    at FSWatcher.emit (node:events:513:28)
    at FSWatcher.emitWithAll (/opt/podman-desktop-bin/resources/app.asar/node_modules/chokidar/index.js:540:8)
```

### Operating system

all

### Version

1.0.x

### Steps to reproduce

ln -s /dev/null ~/.kube/config -f

run podman-desktop

**Comment by benoitf** [comment]
thanks for the report
We should check that file is valid
