### ISSUE TITLE
Force reload in Settings -> Extensions (kube-context) break the podman desktop

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3030]
### Bug description

I was reproducing previous kube-context extension breakage issue (#3029), then I tried to remove kubeconfig file to get over the issue and force-reload the UI ->

![Screenshot_20230627_150233](https://github.com/containers/podman-desktop/assets/19164299/4a97f954-f41f-41d7-a8bf-08ca92fa7061)

Log: [preferences-force-reload.log](https://github.com/containers/podman-desktop/files/11882457/preferences-force-reload.log)

### Operating system

Fedora 37, Windows 10

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

0. Run podman desktop from tarball or from windows executable
1. Reproduce the previous issue with kube-context extension: #3029 
2. Settings -> Extensions -> kube-context 
3. Force reload the page

### Relevant log output

```shell
PreferencesExtensionRendering.svelte:25 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'displayName')
    at QT (PreferencesExtension…dering.svelte:25:37)
    at Se (index.mjs:2180:37)
    at new ex (PreferencesExtension…dering.svelte:11:82)
    at Array.dD (PreferencesPage.svelte:48:74)
    at Kt (index.mjs:71:28)
    at id (Route.svelte:46:38)
    at hw (Route.svelte:45:17)
    at Se (index.mjs:2180:37)
    at new Ge (Route.svelte:41:13)
    at CD (PreferencesPage.svelte:95:30)
QT	@	PreferencesExtensionRendering.svelte:25
Se	@	index.mjs:2180
ex	@	PreferencesExtensionRendering.svelte:11
dD	@	PreferencesPage.svelte:48
Kt	@	index.mjs:71
id	@	Route.svelte:46
hw	@	Route.svelte:45
Se	@	index.mjs:2180
Ge	@	Route.svelte:41
CD	@	PreferencesPage.svelte:95
Se	@	index.mjs:2180
$D	@	PreferencesPage.svelte:33
aV	@	App.svelte:141
Kt	@	index.mjs:71
id	@	Route.svelte:46
hw	@	Route.svelte:45
Se	@	index.mjs:2180
Ge	@	Route.svelte:41
dV	@	App.svelte:73
Kt	@	index.mjs:71
id	@	Route.svelte:46
hw	@	Route.svelte:45
Se	@	index.mjs:2180
Ge	@	Route.svelte:41
hV	@	App.svelte:81
Se	@	index.mjs:2180
mV	@	App.svelte:73
vV	@	SealRocket.svelte:2
p	@	Loader.svelte:69
W7	@	index.mjs:1347
b5	@	index.mjs:1307
Promise.then (async)		
g5	@	index.mjs:1258
Q7	@	index.mjs:2133
(anonymous)	@	index.mjs:2171
(anonymous)	@	Loader.svelte:20
await in (anonymous) (async)		
l5	@	index.mjs:20
(anonymous)	@	index.mjs:2101
b5	@	index.mjs:1329
Se	@	index.mjs:2197
CV	@	Loader.svelte:65
(anonymous)	@	main.ts:3
```

**Comment by benoitf** [comment]
looks similar to https://github.com/containers/podman-desktop/issues/2993 (or a dup)
