### ISSUE TITLE
Unable to fetch the available extensions: getaddrinfo ENOTFOUND registry.podman-desktop.io

### ISSUE THREAD

**Issue by eidottermihi** [containers/podman-desktop#3449]
### Bug description

Apparently the lookup of available extensions fails because the configured Proxy (Settings -> Proxy) is not taken into account for the lookup.

Error in console:
```
Unable to fetch the available extensions: getaddrinfo ENOTFOUND registry.podman-desktop.io
```

![grafik](https://github.com/containers/podman-desktop/assets/2780736/4a4ac68d-8006-45eb-9c66-f9d35cf63e4e)

### Operating system

Windows 10 22H2

### Installation Method

Installer from website/GitHub releases

### Version

1.2.1

### Steps to reproduce

- Run Podman Desktop in environment where a HTTP proxy is needed for internet connectivity
- Configure the proxy in Settings -> Proxy
- Open up "Settings / Extensions"
- Open log -> error log

### Relevant log output

```shell
index.ts:1451 main ↪️ Unable to fetch the available extensions: getaddrinfo ENOTFOUND registry.podman-desktop.io
console.<computed> @ index.ts:1451
index.ts:1451 main ↪️ [kind] HttpError: fetch failed
    at C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kind\builtin\kind.cdix\dist\extension.js:12:8268
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ms (C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kind\builtin\kind.cdix\dist\extension.js:7:10552)
    at async ml (C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kind\builtin\kind.cdix\dist\extension.js:7675:629)
    at async Tz.activateExtension (C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:91:37954)
    at async Tz.loadExtension (C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:91:31603)
    at async Promise.all (index 2)
    at async Tz.loadExtensions (C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:91:28537)
    at async Tz.start (C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:91:27826)
    at async zde.initExtensions (C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:323:48500)
console.<computed> @ index.ts:1451
index.ts:1451 main ↪️ [kind] HttpError: fetch failed
    at C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kind\builtin\kind.cdix\dist\extension.js:12:8268
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ma.isAvailable (C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kind\builtin\kind.cdix\dist\extension.js:14:75460)
    at async ml (C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kind\builtin\kind.cdix\dist\extension.js:7675:680)
    at async Tz.activateExtension (C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:91:37954)
    at async Tz.loadExtension (C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:91:31603)
    at async Promise.all (index 2)
    at async Tz.loadExtensions (C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:91:28537)
    at async Tz.start (C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:91:27826)
    at async zde.initExtensions (C:\Users\michael.prankl\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:323:48500)
```

**Comment by benoitf** [comment]
thanks @eidottermihi for the bug report.
