### ISSUE TITLE
kind extension cannot retrieve release information in a proxy environment

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#3766]
### Bug description

When connected through a proxy, the Kind extension cannot retrieve the release information and cannot be used:

```
index.ts:1506 main ↪️ [kind] HttpError: fetch failed
    at C:\Users\demo\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kind\builtin\kind.cdix\dist\extension.js:12:8268
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async hn (C:\Users\demo\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kind\builtin\kind.cdix\dist\extension.js:7:10552)
    at async fl (C:\Users\demo\AppData\Local\Programs\podman-desktop\resources\app.asar\extensions\kind\builtin\kind.cdix\dist\extension.js:7678:629)
    at async $j.activateExtension (C:\Users\demo\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:91:44909)
    at async $j.loadExtension (C:\Users\demo\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:91:38182)
    at async Promise.all (index 2)
    at async $j.loadExtensions (C:\Users\demo\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:91:34980)
    at async $j.start (C:\Users\demo\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:91:34269)
    at async yhe.initExtensions (C:\Users\demo\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:328:411493)

```

### Operating system

Win10Pro

### Installation Method

Winget (Windows)

### Version

1.3.1

**Comment by benoitf** [comment]
@dgolovin transparent proxy is not added automatically ?

**Comment by jeffmaury** [comment]
Duplicate of #2794
