### ISSUE TITLE
Start error when starting instance of OpenShift Local.

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#4631]
### Bug description

When trying to create an instance of Microshift preset for OS Local, getting this error:
![image](https://github.com/containers/podman-desktop/assets/75624842/bfd36b9d-9a76-4d83-b6a6-f1c6c4c5d684)

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

Install Podman Desktop 1.5.2.
Install OpenShift with microShift preset.
Try to start and initialize from Dashboard or start from Settings.
Error.

### Relevant log output

```shell
VM5:2 main ↪️ [openshift-local] Error: failed to expose port 127.0.0.1:2222 -> 192.168.127.2:22: listen tcp 127.0.0.1:2222: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

    at DaemonCommander.start (C:\Users\rosta\.local\share\containers\podman-desktop\plugins\quayioredhatdeveloperopenshiftlocalextension\dist\extension.js:9367:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startCrc (C:\Users\rosta\.local\share\containers\podman-desktop\plugins\quayioredhatdeveloperopenshiftlocalextension\dist\extension.js:25386:24)
    at async createCrcVm (C:\Users\rosta\.local\share\containers\podman-desktop\plugins\quayioredhatdeveloperopenshiftlocalextension\dist\extension.js:26661:24)
    at async Object.create (C:\Users\rosta\.local\share\containers\podman-desktop\plugins\quayioredhatdeveloperopenshiftlocalextension\dist\extension.js:26641:13)
    at async C:\Users\rosta\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:384:18579
    at async C:\Users\rosta\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:382:16958
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:88640)
```

**Comment by jeffmaury** [comment]
That is a known conflict between Podman (I think user mode networking) and CRC. Issue should be moved there

**Comment by rostalan** [comment]
Reported here: https://github.com/crc-org/crc-extension/issues/188 
closing it here.
