### ISSUE TITLE
Starting failed of a fresh podman machine with user mode networking 

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#5235]
### Bug description

I have created a podman machine with user mode networking. Then I tried to start it and got an error:

![podman_machine_netusermode_start_error125](https://github.com/containers/podman-desktop/assets/19164299/25275ada-c9ac-492e-a00f-86520d0b98a0)

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.6.0

### Steps to reproduce

1. Create podman machine - rootful, dislabe start on create and enable user mode networking.
2. Assert: machine is created
3. Start the machine
4. Assert: Machine is started and we can ie. pull an image
Actual result: error during strat up

### Relevant log output

```shell
Errors in a dev console:

[Violation] Forced reflow while executing JavaScript took 36ms
VM5:2 main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
VM5:2 main ↪️ [podman] Command execution failed with exit code 125: Command execution failed with exit code 125
    at ChildProcess.<anonymous> (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:345:13058)
    at ChildProcess.emit (node:events:514:28)
    at Process.onexit (node:internal/child_process:291:12)
console.<computed> @ VM5:2
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
VM5:2 main ↪️ Aborting reconnect due to error as connection is now stopped
PreferencesConnectionActions.svelte:49 Error: Command execution failed with exit code 125

Machine log: 
[Violation] Forced reflow while executing JavaScript took 36ms
VM5:2 main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
VM5:2 main ↪️ [podman] Command execution failed with exit code 125: Command execution failed with exit code 125
    at ChildProcess.<anonymous> (C:\Users\Ondrej\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:345:13058)
    at ChildProcess.emit (node:events:514:28)
    at Process.onexit (node:internal/child_process:291:12)
console.<computed> @ VM5:2
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
VM5:2 main ↪️ Aborting reconnect due to error as connection is now stopped
PreferencesConnectionActions.svelte:49 Error: Command execution failed with exit code 125
```

### Additional context

I have had a multiple machines created and used. Then they were all stopped and I created a new with user mode net. flag. Then I tried to start it. Errors appeared.

I tried also to enable start on create button and got a bit different error:
```
Error: Command execution failed with exit code 125 Command execution failed with exit code 125 your 131072x1 screen size is bogus. expect trouble Error: error setting up user-mode networking: exit status 42
```

**Comment by odockal** [comment]
Log from when starting from CLI
```
podman machine start podman-machine-default2 --log-level=DEBUG
time="2023-12-12T20:05:12+01:00" level=info msg="C:\\Program Files\\RedHat\\Podman\\podman.exe filtering at log level debug"
time="2023-12-12T20:05:12+01:00" level=debug msg="Using Podman machine with `wsl` virtualization provider"
Starting machine "podman-machine-default2"
time="2023-12-12T20:05:13+01:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default2 sh -c rm -f /etc/systemd/system.conf.d/default-env.conf \\\n\t   /etc/environment.d/default-env.conf \\\n\t   /etc/profile.d/default-env.sh]"
Starting user-mode networking...
time="2023-12-12T20:05:14+01:00" level=debug msg="Running command: wsl [-u root -d podman-net-usermode bash]"
Error: error setting up user-mode networking: exit status 42
time="2023-12-12T20:05:16+01:00" level=debug msg="Shutting down engines"
```

**Comment by jeffmaury** [comment]
Can you try to shutdown wsl as there is a known issue when lots of start/stop machines are done

**Comment by benoitf** [comment]
it's working on my end

**Comment by benoitf** [comment]
if I do first `wsl --unregister podman-net-usermode  ?` 

I'm able to reproduce and I get `exit status 42`

failure is coming from
https://github.com/containers/podman/blob/d8c6ca6c1bbbdda7009cfd403199c2edfa668d60/pkg/machine/wsl/usermodenet.go#L164-L184

**Comment by odockal** [comment]
Problem seems to be tied to a fedora 39 version base image available on https://github.com/containers/podman-wsl-fedora/releases. Fedora 39 are not working, while version fedora 38 based images works.

**Comment by benoitf** [comment]
commented it there https://github.com/containers/podman/issues/20982#issuecomment-1852838422
