### ISSUE TITLE
ERR_INVALID_URL when using `vscode` scheme for openExternal

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#5672]
### Is your enhancement related to a problem? Please describe

In an extension we have a requirements on opening the user's `ide`, since vscode support opening a folder with an uri with the following structure `vscode://{full path to file}`.

### Describe the solution you'd like

Support vscode scheme

### Additional context

Currently using the api raise an error with the following trace

```js
14:56:41 [main] Unable to open external link  vscode://\Users\axels\podman-desktop\ai-studio\chatbot from extension redhat.studio-extension TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:642:13)
    at securityRestrictionCurrentHandler.handler (C:\Users\axels\Documents\github\redhat\podman-desktop\packages\main\dist\index.cjs:121415:25)
    at StudioApiImpl.openVSCode (C:\Users\axels\Documents\github\redhat\studio-extension\packages\backend\dist\extension.js:167:42)
    at C:\Users\axels\Documents\github\redhat\studio-extension\packages\backend\dist\extension.js:62:65
    at C:\Users\axels\Documents\github\redhat\podman-desktop\packages\main\dist\index.cjs:27190:46
    at CallbackList.invoke (C:\Users\axels\Documents\github\redhat\podman-desktop\packages\main\dist\index.cjs:27197:18)
    at Emitter.fire (C:\Users\axels\Documents\github\redhat\podman-desktop\packages\main\dist\index.cjs:27336:23)
    at WebviewImpl.handleMessage (C:\Users\axels\Documents\github\redhat\podman-desktop\packages\main\dist\index.cjs:121010:31) {
  input: 'vscode://\\Users\\axels\\podman-desktop\\ai-studio\\chatbot',
  code: 'ERR_INVALID_URL'
}
```

**Comment by benoitf** [comment]
@axel7083 looking at the VS Code url handler I think you're not giving the right syntax

https://code.visualstudio.com/docs/editor/command-line#_opening-vs-code-with-urls

1. you need to start with `vscode://file/`
1. for the path, it requires slashes / not \\

`vscode://file/Users/axels/podman-desktop/ai-studio/chatbot`

**Comment by benoitf** [comment]
closing as won't fix as it's working as expected by using expected scheme
