### ISSUE TITLE
App freezes after minikube cluster restart and deletion

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop#5826]
### Bug description

After creating cluster and restarting it from its details page, it throws an error (and the restart button keeps spinning) about the container being already started.

This in some cases prevents further app usage.
If I proceed to force refresh in order to keep using the app, and if I stop and delete this cluster from inside cluster details page, the view switches to dashboard and the whole PD app appears unresponsive (fixable with another force refresh).

None of this is present when restarting from Resources page.

### Operating system

fedora 39

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Create new Minikube cluster
2. Go to Minikube details, press Restart button.
3. Assert: cluster restarts
4. Actual: an error is thrown

### Relevant log output

```shell
The error thrown:
VM74:2 main ↪️ [minikube] Error: (HTTP code 304) container already started -  
    at /app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:15:6328
    at A (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:15:6701)
    at rA.buildPayload (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:15:6278)
    at IncomingMessage.<anonymous> (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:15:5812)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
console.<computed> @ VM74:2
(anonymous) @ VM74:2
emit @ VM73 sandbox_bundle:2
onMessage @ VM73 sandbox_bundle:2
```

**Comment by ScrewTSW** [comment]
Doesn't seem to be an issue on the Windows side

**Comment by rostalan** [comment]
Duplicit of [5666](https://github.com/containers/podman-desktop/issues/5666)
