### ISSUE TITLE
Running `Draft` release from Github result in `App version is not a valid semver version`

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#6289]
### Bug description

When starting it I am getting a boot loop on `Initialization` 
<img width="788" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/dadc3658-7139-48bf-8447-6d904ba0faf8">

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

I downloaded `podman-desktop-0.0.202403061436-8166-x64.exe` [releases#8a9bf4aa95aa7f4baab9](https://github.com/containers/podman-desktop/releases/tag/untagged-8a9bf4aa95aa7f4baab9) from the release page.

### Relevant log output

```shell
VM5:2 main ↪️ (node:2132) UnhandledPromiseRejectionWarning: Error: App version is not a valid semver version: "0.0.202403061436-0008166"
    at l (C:\Users\axels\AppData\Local\Temp\2dJqrSeAt21rJ38F3llLJedBIKR\resources\app.asar\packages\main\dist\index.cjs:325:10809)
    at new c6 (C:\Users\axels\AppData\Local\Temp\2dJqrSeAt21rJ38F3llLJedBIKR\resources\app.asar\packages\main\dist\index.cjs:333:8846)
    at new r (C:\Users\axels\AppData\Local\Temp\2dJqrSeAt21rJ38F3llLJedBIKR\resources\app.asar\packages\main\dist\index.cjs:333:17043)
    at new f (C:\Users\axels\AppData\Local\Temp\2dJqrSeAt21rJ38F3llLJedBIKR\resources\app.asar\packages\main\dist\index.cjs:337:24004)
    at d (C:\Users\axels\AppData\Local\Temp\2dJqrSeAt21rJ38F3llLJedBIKR\resources\app.asar\packages\main\dist\index.cjs:337:30074)
    at Object.get [as autoUpdater] (C:\Users\axels\AppData\Local\Temp\2dJqrSeAt21rJ38F3llLJedBIKR\resources\app.asar\packages\main\dist\index.cjs:337:30809)
    at vbe.init (C:\Users\axels\AppData\Local\Temp\2dJqrSeAt21rJ38F3llLJedBIKR\resources\app.asar\packages\main\dist\index.cjs:337:35143)
    at Sbe.initExtensions (C:\Users\axels\AppData\Local\Temp\2dJqrSeAt21rJ38F3llLJedBIKR\resources\app.asar\packages\main\dist\index.cjs:339:456)
    at async C:\Users\axels\AppData\Local\Temp\2dJqrSeAt21rJ38F3llLJedBIKR\resources\app.asar\packages\main\dist\index.cjs:366:3536
```

### Additional context

cc @slemeur

**Comment by jeffmaury** [comment]
Also having a strange design:

![image](https://github.com/containers/podman-desktop/assets/695993/036e5681-988a-4d7c-a7f2-1f4d37157285)

**Comment by benoitf** [comment]
I downloaded the latest published version from https://github.com/containers/podman-desktop/releases/tag/v0.0.202403070840-08a8cf4

and I don't reproduce on macOS

is it only on Windows ?

**Comment by benoitf** [comment]
anyway draft release should not be used, only pre-releases. (draft are not visible to end users)

if it stays as a draft it means there was an issue somewhere

**Comment by axel7083** [comment]
> ```shell
> 0.0.202403061436
> ```

Do not reproduced with the given `pre-release` you provided.
