### ISSUE TITLE
Podman-desktop stays in "initalizing" after starting on Gnome 45 and NixOS

### ISSUE THREAD

**Issue by papanito** [containers/podman-desktop#6339]
### Bug description

When starting podman-desktop it stays on "initializing"

![image](https://github.com/containers/podman-desktop/assets/15034009/908e5bee-9ad0-4522-ab71-d77ab7988356)

### Operating system

Linux 6.7.7 #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar  1 12:42:00 UTC 2024 x86_64 GNU/Linux

### Installation Method

Other

### Version

1.7.0

### Steps to reproduce

run `podman-desktop` on a console and observe the UI

### Relevant log output

```shell
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[68126:0310/103935.145981:ERROR:object_proxy.cc(577)] Failed to call method: org.kde.StatusNotifierWatcher.RegisterStatusNotifierItem: object_path= /StatusNotifierWatcher: org.gnome.gjs.JSError.ValueError: appIndicator is undefined
(node:68126) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'endsWith')
    at /nix/store/pcmwm7y9lal28cw6m5lsgw7kcqrxjvs3-podman-desktop-0.12.0/share/lib/podman-desktop/resources/app.asar/packages/main/dist/index-2fc77038.cjs:37699:43
    at Array.forEach (<anonymous>)
    at ExtensionLoader.loadRuntime (/nix/store/pcmwm7y9lal28cw6m5lsgw7kcqrxjvs3-podman-desktop-0.12.0/share/lib/podman-desktop/resources/app.asar/packages/main/dist/index-2fc77038.cjs:37696:32)
    at ExtensionLoader.loadExtension (/nix/store/pcmwm7y9lal28cw6m5lsgw7kcqrxjvs3-podman-desktop-0.12.0/share/lib/podman-desktop/resources/app.asar/packages/main/dist/index-2fc77038.cjs:37507:26)
    at async Promise.all (index 0)
    at async ExtensionLoader.start (/nix/store/pcmwm7y9lal28cw6m5lsgw7kcqrxjvs3-podman-desktop-0.12.0/share/lib/podman-desktop/resources/app.asar/packages/main/dist/index-2fc77038.cjs:37442:5)
    at async PluginSystem.initExtensions (/nix/store/pcmwm7y9lal28cw6m5lsgw7kcqrxjvs3-podman-desktop-0.12.0/share/lib/podman-desktop/resources/app.asar/packages/main/dist/index-2fc77038.cjs:77929:5)
    at async /nix/store/pcmwm7y9lal28cw6m5lsgw7kcqrxjvs3-podman-desktop-0.12.0/share/lib/podman-desktop/resources/app.asar/packages/main/dist/index-2fc77038.cjs:78172:29
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:68126) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unh
andled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
PluginSystem: received dom-ready event from the UI
Warning: vkCreateInstance: Found no drivers!
Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:101)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:493)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:379)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:301)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:556)
```

**Comment by benoitf** [comment]
Hello @papanito it looks like you're using v0.12.0 which looks like too old

Is it possible to use a recent version of Podman Desktop v1.7.1 ?
https://github.com/containers/podman-desktop/releases/tag/v1.7.1

**Comment by papanito** [comment]
Yeah you are right, I checked the [package version](https://search.nixos.org/packages?channel=unstable&show=podman-desktop&from=0&size=50&sort=relevance&type=packages&query=podman-desktop)  and it's version `0.12.0`

**Comment by benoitf** [comment]
@papanito are you able to use https://github.com/containers/podman-desktop/releases/download/v1.7.1/podman-desktop-1.7.1.tar.gz ?

unpack the .tgz and run the `podman-desktop` binary from there ?

**Comment by papanito** [comment]
@benoitf sorry to not follow up. I did not follow up on this - actually was waiting that the package in nixrepo will be updated.

**Comment by itsrezasoltani** [comment]
> [@papanito](https://github.com/papanito) are you able to use https://github.com/containers/podman-desktop/releases/download/v1.7.1/podman-desktop-1.7.1.tar.gz ?
> 
> unpack the .tgz and run the `podman-desktop` binary from there ?

it's not possible (i mean out of the box) in nixos:

```
[18:49:37] [~/Apps/podman-desktop-1.13.2] ❱❱❱ ./podman-desktop
Could not start dynamically linked executable: ./podman-desktop
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
[18:49:39] [cost 0.012s] ./podman-desktop                                                                                                                                                                                                     

```

**Comment by kachick** [comment]
@papanito How about trying with current nixpkgs version? 

It had been updated to 1.13.2 since nixos-24.11.

https://github.com/NixOS/nixpkgs/pull/343648

**Comment by papanito** [comment]
Yep that work now as expected.
