### ISSUE TITLE
Install docker-compose binary got error message

### ISSUE THREAD

**Issue by ZPOMI** [containers/podman-desktop#6543]
### Bug description

When I use Podman Desktop to follow docker-compose, I encounter an error message related to user permissions, do I need to do any privilege escalation operations on Windows 11? Also, I installed with admin privileges and had the same problem.

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.8.0

### Relevant log output

```shell
VM5:2 main ↪️ [compose] Failed to install 'docker-compose' binary: Error: Failed to execute command: User did not grant permission.
console.<computed>	@	VM5:2
(anonymous)	@	VM5:2
emit	@	VM4 sandbox_bundle:2
onMessage	@	VM4 sandbox_bundle:2
VM5:2 main ↪️ [compose] Error: Failed to execute command: User did not grant permission.
    at C:\Users\*****\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:304:11148
    at C:\Users\*****\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:301:1476
    at ChildProcess.exithandler (node:child_process:414:7)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
console.<computed>	@	VM5:2
(anonymous)	@	VM5:2
emit	@	VM4 sandbox_bundle:2
onMessage	@	VM4 sandbox_bundle:2
```

### Additional context

![podman-compose-failed](https://github.com/containers/podman-desktop/assets/21377894/31334827-be30-4294-afe6-56da0a1fce8e)

**Comment by samolesen** [comment]
+1. I would like to add the the wizard specifically mentions that you will be prompted, which never happened for me:
![image](https://github.com/containers/podman-desktop/assets/3702919/3bb21746-433f-4469-9cdd-1a0824b854fc)

Starting Podman Desktop as administrator does not affect this bug.

**Comment by hyoretsu** [comment]
Please fix this.

**Comment by dgolovin** [comment]
@hyoretsu that is correct observation. There is not need to request for system privileges on windows to copy file to ~/AppData/Local/Microsoft/WindowsApp\Microsoft\WindowsApps. It works with simple fs.syncCp(origin, destination).

**Comment by hyoretsu** [comment]
@dgolovin either that or making sure it requests permission. That happened on my desktop, while I just installed it on my notebook and it asked me just fine.

**Comment by dgolovin** [comment]
@hyoretsu Podman-Desktop is using https://www.npmjs.com/package/sudo-prompt module for privilege elevation. On Windows the sudo module is using vbs/bat/powershell combination, that might not work in case you have powershell execution policy different from default.

What is `Get-ExecutionPolicy -List` prints out for you?

**Comment by hyoretsu** [comment]
@dgolovin

```
        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    RemoteSigned
 LocalMachine    RemoteSigned
```

**Comment by hyoretsu** [comment]
It's worth noting that my desktop does not have `sudo` enabled in Windows 11.

**Comment by dgolovin** [comment]
@hyoretsu good to know, thanks!
PD does not use sudo, `--runAs` option for powershell is being used under the hood of 'sudo' npm module. It is still could be related. I'll check it that the case.

**Comment by TheConen** [comment]
There is zero need for Podman Desktop to ask for admin permissions in this scenario. Copying a file to a folder in `%AppData%` and adding a new entry to the users PATH (not the global system PATH) does not require admin permissions. This would also make Podman Desktop much more usable in restricted corporate environments where admin permissions are not available.

**Comment by Shaolyn68SOC** [comment]
I still have this problem with Kubectl, Kind, and Compose. Even after granting admin privileges.  This bug is not fixed

**Comment by hyoretsu** [comment]
Tbh I switched back to Docker for now, various incompatibilities that needed workarounds kept appearing.
