### ISSUE TITLE
Podman Machine using Hyperv provider cannot be properly stopped with podman 4

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#6667]
### Bug description

We are trying migration paths on windows using hyperv provider. There is a problem when, once the podman machine is created and staterd using hyperv provider, cannot be properly stopped, and thus migration/upgrade between podman v4 and v5 is not done properly.

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.9.0

### Steps to reproduce

1. Install podman desktop 1.9.0
2. Install podman v4.9.4
3. Set env. var. CONTAINER_MACHINE_PROVIDER="hyperv"
4. Start up podman desktop with admin privileges
5. Create and start up new machine (as described here #6668)
6. Assert: Machine is started and image can be pulled
7. Stop the machine
8. Assert: Machine can be stopped
Actual result: Machine appears to be in "Starting" state forever

![Screenshot_20240405_105925](https://github.com/containers/podman-desktop/assets/19164299/4695bbb7-b36f-45e9-b45b-ccae0b7746f0)

Hyperv Manager shows machine as stopped:

![Screenshot_20240405_110306](https://github.com/containers/podman-desktop/assets/19164299/3b63223a-ad8f-4827-a4b9-fa2584512f90)

### Relevant log output

```shell
### Logs from Podman Desktop:
main ↪️ error is Error: connect ENOENT \\.\pipe\podman-machine-default
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)

Error when handling events Error: Error in handling events
    at Object.callback (C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:130:3229)
    at C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:119:48474
    at _o.buildPayload (C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:96:6247)
    at ClientRequest.<anonymous> (C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:96:5930)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketErrorListener (node:_http_client:495:9)
    at Socket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) Will reconnect in 5s Error: Error in handling events
    at Object.callback (C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:130:3229)
    at C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:119:48474
    at _o.buildPayload (C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:96:6247)
    at ClientRequest.<anonymous> (C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:96:5930)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketErrorListener (node:_http_client:495:9)
    at Socket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)


### Logs from podman:
podman machine ls
NAME                     VM TYPE     CREATED         LAST UP             CPUS        MEMORY      DISK SIZE
podman-machine-default*  hyperv      13 minutes ago  Currently starting  2           2GiB        100GiB

podman system connection ls
Name                         URI                                                          Identity                                       Default
podman-machine-default       ssh://core@127.0.0.1:56467/run/user/1000/podman/podman.sock  C:\Users\podmanqe\.ssh\podman-machine-default  true
podman-machine-default-root  ssh://root@127.0.0.1:56467/run/podman/podman.sock            C:\Users\podmanqe\.ssh\podman-machine-default  false

podman version
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: dial tcp 127.0.0.1:56467: connectex: No connection could be made because the target machine actively refused it.

podman -v
podman.exe version 4.9.4
```

**Comment by odockal** [comment]
Trying to stop the machine via cli brings this outcome:
```
podman machine ls --log-level=debug
time="2024-04-05T02:01:26-07:00" level=info msg="C:\\Program Files\\RedHat\\Podman\\podman.exe filtering at log level debug"
time="2024-04-05T02:01:26-07:00" level=debug msg="Using Podman machine with `hyperv` virtualization provider"
NAME                     VM TYPE     CREATED         LAST UP             CPUS        MEMORY      DISK SIZE
podman-machine-default*  hyperv      16 minutes ago  Currently starting  2           2GiB        100GiB
time="2024-04-05T02:01:26-07:00" level=debug msg="Called machine list.PersistentPostRunE(C:\\Program Files\\RedHat\\Podman\\podman.exe machine ls --log-level=debug)"
time="2024-04-05T02:01:26-07:00" level=debug msg="Shutting down engines"

PS C:\Users\podmanqe\AppData\Local\Microsoft\WindowsApps> podman machine stop --log-level=debug
time="2024-04-05T02:01:46-07:00" level=info msg="C:\\Program Files\\RedHat\\Podman\\podman.exe filtering at log level debug"
time="2024-04-05T02:01:46-07:00" level=debug msg="Using Podman machine with `hyperv` virtualization provider"
Machine "podman-machine-default" stopped successfully
time="2024-04-05T02:01:46-07:00" level=debug msg="Called machine stop.PersistentPostRunE(C:\\Program Files\\RedHat\\Podman\\podman.exe machine stop --log-level=debug)"
time="2024-04-05T02:01:46-07:00" level=debug msg="Shutting down engines"
```

**Comment by benoitf** [comment]
you should probably never use 
```
Set env. var. CONTAINER_MACHINE_PROVIDER="hyperv"
```

doing that, only the CLI is aware that you're using hyperv


```toml
[machine]
provider="hyperv"
```

to ~/.config/containers/containers.conf

is the way to have it being seen by all the processes

**Comment by odockal** [comment]
@benoitf The env. var. is set via user env. variables on windows and I am hoping that it is available in podman-desktop as well. When I created a machine using this env. var.:
![Screenshot_20240405_113519](https://github.com/containers/podman-desktop/assets/19164299/a645c947-9120-45ed-9407-c728bec5fd25)

I then can see the machine config via cli:
```
podman machine ls --format json
[
    {
        "Name": "podman-machine-default",
        "Default": false,
        "Created": "2024-04-05T02:29:33.4709352-07:00",
        "Running": false,
        "Starting": false,
        "LastUp": "0001-01-01T00:00:00Z",
        "Stream": "custom",
        "VMType": "hyperv",
        "CPUs": 0,
        "Memory": "0",
        "DiskSize": "0",
        "Port": 0,
        "RemoteUsername": "core",
        "IdentityPath": "",
        "UserModeNetworking": false
    }
]
```

So it is not like I am on cli and set it there. Maybe I am just unclear about how to set it  up, but this way (settings it via User's env. vars.) is correct, right?

**Comment by benoitf** [comment]
it's not sure the env is being seen in Podman Desktop

for example if you didn't reboot/restart the session, etc.

**Comment by odockal** [comment]
but it says `VMType: "hyperv"`. I can still try `containers.conf`.

**Comment by odockal** [comment]
@benoitf The user env. var. works nice. If I remove it and restart podman desktop, it does not see the machine. If set env.var again and restart podman desktop, machine is visible again.

**Comment by odockal** [comment]
I do not observe this behavior with Podman 5.1.0 client anymore.
