### ISSUE TITLE
Not start with listen on all interface and with VPN ikev2/ipsec

### ISSUE THREAD

**Issue by agrisvv** [containers/podman-desktop#6843]
### Bug description

Podman 1.9.1 not fully load then connected to VPN ikev2/ipec (client are strongswan). With l2tp/ipsec works ok.
1.8.0 works ok.
i think related to: https://github.com/containers/podman-desktop/pull/6354

ifconfig:
````
nm-xfrm-6960963: flags=193<UP,RUNNING,NOARP>  mtu 1400
        inet 10.2.5.200  netmask 255.255.255.255
        inet6 fe80::6c40:e009:d88c:61bd  prefixlen 64  scopeid 0x20<link>
`````
nmcli:

````
xxxx-IKEV2 VPN connection
        master bridge0, VPN
        inet4 10.2.5.200/32
        inet6 fe80::6c40:e009:d88c:61bd/64
        route6 fe80::/64 metric 256
````

### Operating system

linux fedora 39

### Installation Method

Flathub (Linux)

### Version

1.9.0

### Steps to reproduce

turn on VPN ikev2/ipsec strongswan.
start podman-desktop.

### Relevant log output

```shell
./podman-desktop
(node:18155) UnhandledPromiseRejectionWarning: RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received type number (65536).
    at new NodeError (node:internal/errors:406:5)
    at validatePort (node:internal/validators:409:11)
    at Server.listen (node:net:2000:5)
    at /var/lib/flatpak/app/io.podman_desktop.PodmanDesktop/x86_64/stable/0950a1e249a66b258b7bbc6602335ad8e4f6a147913427976d6590c03feb82a6/files/main/resources/app.asar/packages/main/dist/index.cjs:135:998
    at new Promise (<anonymous>)
    at v2 (/var/lib/flatpak/app/io.podman_desktop.PodmanDesktop/x86_64/stable/0950a1e249a66b258b7bbc6602335ad8e4f6a147913427976d6590c03feb82a6/files/main/resources/app.asar/packages/main/dist/index.cjs:135:890)
    at nS (/var/lib/flatpak/app/io.podman_desktop.PodmanDesktop/x86_64/stable/0950a1e249a66b258b7bbc6602335ad8e4f6a147913427976d6590c03feb82a6/files/main/resources/app.asar/packages/main/dist/index.cjs:135:1059)
    at rS (/var/lib/flatpak/app/io.podman_desktop.PodmanDesktop/x86_64/stable/0950a1e249a66b258b7bbc6602335ad8e4f6a147913427976d6590c03feb82a6/files/main/resources/app.asar/packages/main/dist/index.cjs:135:717)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async nwe.start (/var/lib/flatpak/app/io.podman_desktop.PodmanDesktop/x86_64/stable/0950a1e249a66b258b7bbc6602335ad8e4f6a147913427976d6590c03feb82a6/files/main/resources/app.asar/packages/main/dist/index.cjs:337:18118)
    at emitUnhandledRejectionWarning (node:internal/process/promises:201:15)
    at processPromiseRejections (node:internal/process/promises:297:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:18155) RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received type number (65536).
    at new NodeError (node:internal/errors:406:5)
    at validatePort (node:internal/validators:409:11)
    at Server.listen (node:net:2000:5)
    at /var/lib/flatpak/app/io.podman_desktop.PodmanDesktop/x86_64/stable/0950a1e249a66b258b7bbc6602335ad8e4f6a147913427976d6590c03feb82a6/files/main/resources/app.asar/packages/main/dist/index.cjs:135:998
    at new Promise (<anonymous>)
    at v2 (/var/lib/flatpak/app/io.podman_desktop.PodmanDesktop/x86_64/stable/0950a1e249a66b258b7bbc6602335ad8e4f6a147913427976d6590c03feb82a6/files/main/resources/app.asar/packages/main/dist/index.cjs:135:890)
    at nS (/var/lib/flatpak/app/io.podman_desktop.PodmanDesktop/x86_64/stable/0950a1e249a66b258b7bbc6602335ad8e4f6a147913427976d6590c03feb82a6/files/main/resources/app.asar/packages/main/dist/index.cjs:135:1059)
    at rS (/var/lib/flatpak/app/io.podman_desktop.PodmanDesktop/x86_64/stable/0950a1e249a66b258b7bbc6602335ad8e4f6a147913427976d6590c03feb82a6/files/main/resources/app.asar/packages/main/dist/index.cjs:135:717)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async nwe.start (/var/lib/flatpak/app/io.podman_desktop.PodmanDesktop/x86_64/stable/0950a1e249a66b258b7bbc6602335ad8e4f6a147913427976d6590c03feb82a6/files/main/resources/app.asar/packages/main/dist/index.cjs:337:18118)
```

**Comment by agrisvv** [comment]
Problem stil exist on podman v1.13.2 and fedora 40.

**Comment by agrisvv** [comment]
Problem still exist podman desktop 1.18 fedora 41.

**Comment by rujutashinde** [comment]
Could you please try with the latest podman-desktop version, if it still persists , please reopen.

**Comment by agrisvv** [comment]
Don't have perms to reopen. @rujutashinde 
Still same with podman desktop 1.27.1 on fedora 43. No difference flatpak or simple bin.

when VPN are ON ( stuck at initialize):
```
apr 29 18:27:00 pc-name systemd[2802]: Started app-flatpak-io.podman_desktop.PodmanDesktop-2924663204.scope.
apr 29 18:27:00 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: [3:0429/182700.940733:ERROR:dbus/bus.cc:405] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: (node:3) ExperimentalWarning: SQLite is an experimental feature and might change at any time
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: (Use `podman-desktop --trace-warnings ...` to show where the warning was created)
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: (node:3) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
apr 29 18:27:01 pc-name podman-desktop[744727]: Failed to load module "pk-gtk-module"
apr 29 18:27:01 pc-name podman-desktop[744727]: Failed to load module "pk-gtk-module"
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: [3:0429/182701.527972:ERROR:dbus/bus.cc:405] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: [3:0429/182701.527991:ERROR:dbus/bus.cc:405] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744789]: LaunchProcess: failed to execvp:
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744789]: xdg-settings
apr 29 18:27:01 pc-name appindicatorsupport@rgcjonas.gmail.com[3144]: Podman Desktop_status_icon_1, Impossible to lookup icon for 'status_icon_0' in /run/user/1000/app/io.podman_desktop.PodmanDesktop/org.chromium.Chromium.7SF7xN
apr 29 18:27:01 pc-name appindicatorsupport@rgcjonas.gmail.com[3144]: Podman Desktop_status_icon_1, Impossible to lookup icon for 'status_icon_0' in /run/user/1000/app/io.podman_desktop.PodmanDesktop/org.chromium.Chromium.7SF7xN
apr 29 18:27:01 pc-name appindicatorsupport@rgcjonas.gmail.com[3144]: Podman Desktop_status_icon_1, Impossible to lookup icon for 'status_icon_0' in /run/user/1000/app/io.podman_desktop.PodmanDesktop/org.chromium.Chromium.7SF7xN
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: [Managed-by]: No managed defaults file found at /run/host/usr/share/podman-desktop/default-settings.json
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: [Managed-by]: No managed locked file found at /run/host/usr/share/podman-desktop/locked.json
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: (node:3) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: Error occurred in handler for 'configuration-registry:getConfigurationValue': Error: No handler registered for 'configuration-registry:getConfigurationValue'
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]:     at Session.<anonymous> (node:electron/js2c/browser_init:2:116002)
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]:     at Session.emit (node:events:508:28)
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: Error occurred in handler for 'configuration-registry:getConfigurationValue': Error: No handler registered for 'configuration-registry:getConfigurationValue'
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]:     at Session.<anonymous> (node:electron/js2c/browser_init:2:116002)
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]:     at Session.emit (node:events:508:28)
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: Error occurred in handler for 'configuration-registry:getConfigurationValue': Error: No handler registered for 'configuration-registry:getConfigurationValue'
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]:     at Session.<anonymous> (node:electron/js2c/browser_init:2:116002)
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]:     at Session.emit (node:events:508:28)
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: Error occurred in handler for 'experimental-configuration-manager:isExperimentalConfigurationEnabled': Error: No handler registered for 'experimental-configuration-manager:isExperimentalConfigurationEnabled'
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]:     at Session.<anonymous> (node:electron/js2c/browser_init:2:116002)
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]:     at Session.emit (node:events:508:28)
apr 29 18:27:01 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: PluginSystem: received dom-ready event from the UI
apr 29 18:27:04 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: (node:3) UnhandledPromiseRejectionWarning: Error: Unable to find a free port: all ports in the valid range (1024-65535) are busy.
apr 29 18:27:04 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]:     at getFreePort (/app/main/resources/app.asar/packages/main/dist/index.cjs:232:9375)
apr 29 18:27:04 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]:     at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
apr 29 18:27:04 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]:     at async WebviewRegistry.start (/app/main/resources/app.asar/packages/main/dist/index.cjs:236:49715)
apr 29 18:27:04 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]:     at async PluginSystem.initExtensions (/app/main/resources/app.asar/packages/main/dist/index.cjs:313:2069)
apr 29 18:27:04 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]:     at async /app/main/resources/app.asar/packages/main/dist/index.cjs:313:56212
apr 29 18:27:04 pc-name io.podman_desktop.PodmanDesktop.desktop[744727]: (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

```

Ad this is then VPN are OFF ( it started normally):
```
apr 29 18:30:58 pc-name systemd[2802]: Started app-flatpak-io.podman_desktop.PodmanDesktop-3698757459.scope.
apr 29 18:30:58 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: [3:0429/183058.678465:ERROR:dbus/bus.cc:405] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: (node:3) ExperimentalWarning: SQLite is an experimental feature and might change at any time
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: (Use `podman-desktop --trace-warnings ...` to show where the warning was created)
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: (node:3) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
apr 29 18:30:59 pc-name podman-desktop[747639]: Failed to load module "pk-gtk-module"
apr 29 18:30:59 pc-name podman-desktop[747639]: Failed to load module "pk-gtk-module"
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: [3:0429/183059.258226:ERROR:dbus/bus.cc:405] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: [3:0429/183059.258245:ERROR:dbus/bus.cc:405] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747705]: LaunchProcess: failed to execvp:
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747705]: xdg-settings
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: [Managed-by]: No managed defaults file found at /run/host/usr/share/podman-desktop/default-settings.json
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: [Managed-by]: No managed locked file found at /run/host/usr/share/podman-desktop/locked.json
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Starting http server to handle webviews on port 44000
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: System ready. Loading extensions...
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: (node:3) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: [podman-desktop.compose]: Missing suffix 'Failure' for the step 'versionCheckFailedView' that has a 'failed' state
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.compose) with max activation time of 20 seconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: PluginSystem: received dom-ready event from the UI
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Delayed startup, flushing 14 events
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.compose) ended in 161 milliseconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.docker) with max activation time of 20 seconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.docker) ended in 9 milliseconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Extension (podman-desktop.kind) not activated because it is disabled
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.kube-context) with max activation time of 20 seconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: [kube-context] starting extension kube-context
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.kube-context) ended in 44 milliseconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.kubectl-cli) with max activation time of 20 seconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.kubectl-cli) ended in 33 milliseconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.lima) with max activation time of 20 seconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: [lima] Could not find socket at /sock
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.lima) ended in 2 milliseconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.podman) with max activation time of 20 seconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.podman) ended in 64 milliseconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.podman-docker-context) with max activation time of 20 seconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.podman-docker-context) ended in 0 milliseconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.registries) with max activation time of 20 seconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Activating extension (podman-desktop.registries) ended in 0 milliseconds
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: PluginSystem: initialization done.
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Autostarting podman-desktop.podman container engine
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: [kubectl-cli] Error getting kubectl from user PATH: Command execution failed with exit code 1: Command execution failed with exit code 1, trying from extension storage path
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: [kubectl-cli] Error getting kubectl version system from extension storage path Command execution failed with exit code 1: Command execution failed with exit code 1
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]:     at ChildProcess.<anonymous> (/app/main/resources/app.asar/packages/main/dist/image-registry-Dtc_TWdF.cjs:178:13601)
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]:     at ChildProcess.emit (node:events:508:28)
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]:     at maybeClose (node:internal/child_process:1100:16)
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]:     at Socket.<anonymous> (node:internal/child_process:457:11)
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]:     at Socket.emit (node:events:508:28)
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]:     at Pipe.<anonymous> (node:net:346:12) {
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]:   exitCode: 1,
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]:   command: 'flatpak-spawn',
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]:   stdout: '',
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]:   stderr: 'Portal call failed: Failed to start command: Failed to execute child process “/home/xxxxx/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.kubectl-cli/bin/kubectl” (No such file or directory)',
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]:   cancelled: false,
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]:   killed: false
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: }
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Fetched https://registry.podman-desktop.io/api/extensions.json in 519.637978ms
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Fetched https://registry.podman-desktop.io/api/extensions.json in 393.399911ms
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Fetched https://registry.podman-desktop.io/api/extensions.json in 384.45053999999993ms
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Fetched https://registry.podman-desktop.io/api/extensions.json in 139.3495499999999ms
apr 29 18:30:59 pc-name io.podman_desktop.PodmanDesktop.desktop[747639]: Fetched https://registry.podman-desktop.io/api/extensions.json in 41.57783500000005ms
apr 29 18:31:01 pc-name systemd[2802]: app-flatpak-io.podman_desktop.PodmanDesktop-3698757459.scope: Consumed 760ms CPU time, 136.1M memory peak.
```

**Comment by rujutashinde** [comment]
reopening as issue still persists

**Comment by rujutashinde** [comment]
@jiridostal i dont think this is related to `forward` label. removing it . have assigned it for next sprint though
