### ISSUE TITLE
cannot remove an extension in `failed` state

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#6990]
### Bug description

![image](https://github.com/containers/podman-desktop/assets/42176370/063de5a8-0eb6-448e-b190-5359e5cfc638)

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

Install extension pack, and weirdly have an extension in a failed state prevents me to delete it

**Comment by odockal** [comment]
This enhancement/bug fix could be really beneficial as there could be a situation when I am not able to remove extension whatsoever. I have dev sandbox with error, that even podman desktop restart did not solve.
```
Error: Cannot find module 'tslib' Require stack: - C:\Users\podmanqe\.local\share\containers\podman-desktop\plugins\ghcrioredhatdeveloperpodmandesktopsandboxext\node_modules\@kubernetes\client-node\dist\index.js - C:\Users\podmanqe\.local\share\containers\podman-desktop\plugins\ghcrioredhatdeveloperpodmandesktopsandboxext\dist\extension.js - C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs -
Stack trace:
Error: Cannot find module 'tslib'
Require stack:
- C:\Users\podmanqe\.local\share\containers\podman-desktop\plugins\ghcrioredhatdeveloperpodmandesktopsandboxext\node_modules\@kubernetes\client-node\dist\index.js
- C:\Users\podmanqe\.local\share\containers\podman-desktop\plugins\ghcrioredhatdeveloperpodmandesktopsandboxext\dist\extension.js
- C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1151:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:120281)
    at Module._load (node:internal/modules/cjs/loader:992:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at _module._load (C:\Users\podmanqe\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:146:33441)
    at Module.require (node:internal/modules/cjs/loader:1242:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\podmanqe\.local\share\containers\podman-desktop\plugins\ghcrioredhatdeveloperpodmandesktopsandboxext\node_modules\@kubernetes\client-node\dist\index.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1391:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1451:10)
```

I had to quit podman-desktop, and remove manually `~/.local/share/containers/podman-desktop/plugins/extensionlongname` folder.
