### ISSUE TITLE
Red Hat Extensions no longer showing

### ISSUE THREAD

**Issue by u849296** [containers/podman-desktop#7217]
### Bug description

On fresh install, loaded RH Extensions and all options installed including crc.  I removed the extensions and now I cannot find how to install again.  I completely deleted podman-desktop, podman and supporting files but still I do not see this extension.  The Catalog under Settings is also blank with an error in logs showing self-signed cert is not valid.

### Operating system

OSX 14.4.1

### Installation Method

Brew (macOS)

### Version

1.10.2

### Steps to reproduce

Installed RH Extensions then use Extensions Tab to remove same services.  Try to install or see RH extensions again.

### Relevant log output

```shell
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extensions-started listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extension-started listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extension-stopped listeners added. Use emitter.setMaxListeners() to increase limit
main ↪️ Starting http server to handle webviews on port 44000
main ↪️ System ready. Loading extensions...
main ↪️ PluginSystem: received dom-ready event from the UI
main ↪️ Delayed startup, flushing 6 events
main ↪️ An error happened when loading kubeconfig file at /Users/u849296/.kube/config Error: clusters[0].name is missing
main ↪️ An error happened when loading kubeconfig file at /Users/u849296/.kube/config Error: clusters[0].name is missing
main ↪️ Activating extension (podman-desktop.compose) with max activation time of 20 seconds
main ↪️ Activating extension (podman-desktop.docker) with max activation time of 20 seconds
main ↪️ Activating extension (podman-desktop.kind) with max activation time of 20 seconds
main ↪️ Activating extension (podman-desktop.kube-context) with max activation time of 20 seconds
main ↪️ [kube-context] starting extension kube-context
main ↪️ Activating extension (podman-desktop.kubectl-cli) with max activation time of 20 seconds
main ↪️ Activating extension (podman-desktop.lima) with max activation time of 20 seconds
main ↪️ [lima] Could not find socket at /Users/u849296/.lima/podman/sock/podman.sock
main ↪️ Activating extension (podman-desktop.podman) with max activation time of 20 seconds
main ↪️ Activating extension (podman-desktop.registries) with max activation time of 20 seconds
main ↪️ Activating extension (podman-desktop.docker) ended in 151 milliseconds
main ↪️ Activating extension (podman-desktop.lima) ended in 50 milliseconds
main ↪️ Activating extension (podman-desktop.registries) ended in 13 milliseconds
main ↪️ Activating extension (podman-desktop.compose) ended in 558 milliseconds
main ↪️ [kind] kind extension is active
main ↪️ Activating extension (podman-desktop.kind) ended in 509 milliseconds
main ↪️ Activating extension (podman-desktop.kubectl-cli) ended in 483 milliseconds
main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT /var/run/docker.sock
main ↪️ [compose] Error getting compose version: Error: Failed to execute command: spawn /Users/u849296/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.compose/bin/docker-compose ENOENT
main ↪️ Unable to fetch the available extensions: certificate has expired
main ↪️ [kind] kind extension is active
main ↪️ [kind] kind extension is active
main ↪️ [kind] kind extension is active
main ↪️ [kind] kind extension is active
main ↪️ Unable to fetch the available extensions: certificate has expired
main ↪️ Unable to fetch the available extensions: certificate has expired
main ↪️ Activating extension (podman-desktop.kube-context) ended in 735 milliseconds
main ↪️ Activating extension (podman-desktop.podman) ended in 780 milliseconds
main ↪️ PluginSystem: initialization done.
main ↪️ Autostarting podman-desktop.podman container engine
main ↪️ [kind] kind extension is active
main ↪️ Unable to fetch the available extensions: certificate has expired
main ↪️ Unable to fetch the available extensions: certificate has expired
main ↪️ [podman] unable to check from which path podman is coming Error: Command execution failed with exit code 1
main ↪️ Trace: [podman] unable to check from which path podman is coming Command execution failed with exit code 1: Command execution failed with exit code 1 at ChildProcess.<anonymous> (/Users/u849296/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:336:13044) at ChildProcess.emit (node:events:518:28) at ChildProcess._handle.onexit (node:internal/child_process:294:12) { exitCode: 1, command: 'which', stdout: '', stderr: '', cancelled: false, killed: false } at /Users/u849296/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:336:21164 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
main ↪️ [podman] unable to check qemu version Error: Failed to execute command: spawn qemu-system-x86_64 ENOENT
main ↪️ Trace: [podman] unable to check qemu version yc [Error]: Failed to execute command: spawn qemu-system-x86_64 ENOENT at ChildProcess.<anonymous> (/Users/u849296/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:336:12753) at ChildProcess.emit (node:events:518:28) at ChildProcess._handle.onexit (node:internal/child_process:292:12) at onErrorNT (node:internal/child_process:484:16) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { exitCode: 1, command: 'qemu-system-x86_64', stdout: '', stderr: '', cancelled: false, killed: false } at /Users/u849296/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:336:21164 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT /var/run/docker.sock
main ↪️ Unable to fetch the available extensions: certificate has expired
main ↪️ Unable to fetch the available extensions: certificate has expired
main ↪️ Unable to fetch the available extensions: certificate has expired
```

### Additional context

<img width="1076" alt="Screenshot 2024-05-14 at 3 05 15 PM" src="https://github.com/containers/podman-desktop/assets/66442286/76a00d73-df93-40d6-a1fd-f318d2c20da2">
<img width="1740" alt="Screenshot 2024-05-14 at 3 06 02 PM" src="https://github.com/containers/podman-desktop/assets/66442286/7e47e262-6c88-4288-8b42-122a3ac2f40c">
<img width="1503" alt="Screenshot 2024-05-14 at 3 06 19 PM" src="https://github.com/containers/podman-desktop/assets/66442286/9a51e591-e18f-41ed-996a-4b503a4af969">

**Comment by benoitf** [comment]
hello @u849296 do you have troubles accessing https://registry.podman-desktop.io/api/extensions.json ? or was it a GitHub outage

**Comment by u849296** [comment]
I have no issues accessing that URL or github.  I am just not able to reinstall or have the RH Extensions plugin option or see any catalog extensions

**Comment by benoitf** [comment]
@u849296 do you have exited Podman Desktop (like click on the tray icon and then Quit) ?

**Comment by u849296** [comment]
Yes and rebooted plus complete uninstall and reinstall of podman and podman-desktop

**Comment by benoitf** [comment]
@u849296 could you check the date of your system, also if you open the dev console inside Podman Desktop (Command + Option + i on macOS)

and in the console you enter
```
await fetch('https://registry.podman-desktop.io/api/extensions.json')
```

does it work ?

**Comment by gerroon** [comment]
I have the same issue, it seems like the Podman Desktop app isn't respecting the proxy settings that I set under settings-> proxy

**Comment by benoitf** [comment]
hello @gerroon how do you specify proxy settings

also is it a proxy requiring authentication ?

**Comment by gerroon** [comment]
@benoitf I did under the proxy settings. It requires no auth, it is a local network proxy (Privoxy).

Bear in mind that this Win 10 PC doesn't have direct internet, the proxy is the only way to connect it. So if you try it you need to test it without direct connection, or else the app might still be bypassing the proxy.

![Image](https://github.com/user-attachments/assets/4118f30f-2b92-4def-a7b4-512f953a93e6)

![Image](https://github.com/user-attachments/assets/63807639-809c-4f0b-b0d0-da499faf1c14)


Podman v5.3.1 Win 10x64
```
main ↪️ Starting http server to handle webviews on port 44000
main ↪️ System ready. Loading extensions...
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extensions-started listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extension-started listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extension-stopped listeners added. Use emitter.setMaxListeners() to increase limit
main ↪️ Activating extension (podman-desktop.compose) with max activation time of 20 seconds
main ↪️ Error: Error: net::ERR_ADDRESS_UNREACHABLE at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:118396) at SimpleURLLoaderWrapper.emit (node:events:518:28)
main ↪️ unable to check for updates Error: net::ERR_ADDRESS_UNREACHABLE
main ↪️ unable to check for updates Error: net::ERR_ADDRESS_UNREACHABLE
main ↪️ Error: Unable to fetch the available extensions: certificate has expired
main ↪️ PluginSystem: received dom-ready event from the UI
main ↪️ Delayed startup, flushing 10 events
main ↪️ Error: Unable to fetch the available extensions: certificate has expired
main ↪️ Error: Unable to fetch the available extensions: certificate has expired
main ↪️ Activating extension (podman-desktop.compose) ended in 588 milliseconds
main ↪️ Activating extension (podman-desktop.docker) with max activation time of 20 seconds
main ↪️ Activating extension (podman-desktop.docker) ended in 17 milliseconds
main ↪️ Activating extension (podman-desktop.kind) with max activation time of 20 seconds
main ↪️ [kind] kind extension is active
main ↪️ [kind] kind extension is active
main ↪️ Activating extension (podman-desktop.kind) ended in 1735 milliseconds
main ↪️ Activating extension (podman-desktop.kube-context) with max activation time of 20 seconds
main ↪️ [kube-context] starting extension kube-context
main ↪️ Activating extension (podman-desktop.kube-context) ended in 1 milliseconds
main ↪️ Activating extension (podman-desktop.kubectl-cli) with max activation time of 20 seconds
main ↪️ Activating extension (podman-desktop.kubectl-cli) ended in 475 milliseconds
main ↪️ Activating extension (podman-desktop.lima) with max activation time of 20 seconds
main ↪️ [lima] Could not find socket at C:\Users\USER\.lima\podman\sock\podman.sock
main ↪️ Activating extension (podman-desktop.lima) ended in 2 milliseconds
main ↪️ Activating extension (podman-desktop.podman) with max activation time of 20 seconds
main ↪️ [kind] kind extension is active
main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
main ↪️ Activating extension (podman-desktop.podman) ended in 1269 milliseconds
main ↪️ Activating extension (podman-desktop.registries) with max activation time of 20 seconds
main ↪️ Activating extension (podman-desktop.registries) ended in 1 milliseconds
main ↪️ PluginSystem: initialization done.
main ↪️ Autostarting podman-desktop.podman container engine
main ↪️ [kind] kind extension is active
main ↪️ Error: Unable to fetch the available extensions: certificate has expired
main ↪️ Error: Unable to fetch the available extensions: certificate has expired
main ↪️ Error: Unable to fetch the available extensions: certificate has expired
```
