### ISSUE TITLE
Uncaught TypeError: Failed to construct 'FormData' in console after creating second podman machine on Mac 

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#7810]
### Bug description

I spotted a couple of error in dev console when I was creating second podman machine, that was rootfull. Not sure if this plays any role here, might be just a creating of podman machine. Everything seems to work though.

### Operating system

mac OS 14.5

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Relevant log output

```shell
VM5:2 main ↪️ [podman]  Can't get machine rootfull resource usage error Error: no engine matching this container
console.<computed> @ VM5:2
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
VM5:2 main ↪️ Engine does not have an API or a libpod API, returning empty array Podman
VM5:2 main ↪️ [podman] unable to check qemu version Error: Failed to execute command: spawn qemu-system-aarch64 ENOENT
    at ChildProcess.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:337:12755)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
console.<computed> @ VM5:2
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
VM5:2 main ↪️ Trace: [podman] unable to check qemu version pc [Error]: Failed to execute command: spawn qemu-system-aarch64 ENOENT
    at ChildProcess.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:337:12755)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  exitCode: 1,
  command: 'qemu-system-aarch64',
  stdout: '',
  stderr: '',
  cancelled: false,
  killed: false
}
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:337:21166
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
console.<computed> @ VM5:2
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
PreferencesConnectionCreationOrEditRendering.svelte:210 Uncaught (in promise) TypeError: Failed to construct 'FormData': parameter 1 is not of type 'HTMLFormElement'.
    at Q (PreferencesConnectionCreationOrEditRendering.svelte:210:17)
    at E (PreferencesRenderingItemFormat.svelte:109:3)
    at r.$$.update (FileItem.svelte:22:5)
    at he (Component.js:144:5)
    at new sme (FileItem.svelte:24:20)
    at Array.Cme (PreferencesRenderingItemFormat.svelte:139:54)
    at Array.bme (PreferencesRenderingItemFormat.svelte:138:52)
    at Rme (PreferencesRenderingItemFormat.svelte:143:39)
    at he (Component.js:148:34)
    at new Lp (PreferencesRenderingItemFormat.svelte:33:34)
Q @ PreferencesConnectionCreationOrEditRendering.svelte:210
E @ PreferencesRenderingItemFormat.svelte:109
r.$$.update @ FileItem.svelte:22
he @ Component.js:144
sme @ FileItem.svelte:24
Cme @ PreferencesRenderingItemFormat.svelte:139
bme @ PreferencesRenderingItemFormat.svelte:138
Rme @ PreferencesRenderingItemFormat.svelte:143
he @ Component.js:148
Lp @ PreferencesRenderingItemFormat.svelte:33
b7 @ PreferencesConnectionCreationOrEditRendering.svelte:507
$7 @ PreferencesConnectionCreationOrEditRendering.svelte:511
Ume @ PreferencesConnectionCreationOrEditRendering.svelte:496
Nme @ PreferencesConnectionCreationOrEditRendering.svelte:444
p @ PreferencesConnectionCreationOrEditRendering.svelte:537
fU @ scheduler.js:119
VE @ scheduler.js:79
Promise.then (async)
DE @ scheduler.js:20
dU @ Component.js:81
(anonymous) @ Component.js:139
(anonymous) @ TaskManager.svelte:53
i @ index.js:56
l @ index.js:69
i0 @ tasks.ts:36
Zde @ preferences-connection-rendering-task.ts:96
ce @ PreferencesConnectionCreationOrEditRendering.svelte:291
Se @ PreferencesConnectionCreationOrEditRendering.svelte:436
(anonymous) @ lifecycle.js:181
vn @ lifecycle.js:181
k @ Button.svelte:25
Show 11 more frames
Show less
```

### Additional context

Full log: 
[pd-1.11.1-console-errors.log](https://github.com/user-attachments/files/15967607/pd-1.11.1-console-errors.log)

**Comment by jeffmaury** [comment]
Duplicates #7755
