### ISSUE TITLE
containers not showing

### ISSUE THREAD

**Issue by tazihad** [containers/podman-desktop#869]
### Bug description

Suddenly containers stopped showing in containers tab.

### Operating system

Fedora Silverblue 37

### Version

0.9.1

### Relevant log output

console error in containers tab:
```
main ↪️ error in engine Podman Error: (HTTP code 500) server error - getting container from store "4b57521d695e000448b32ccaa44f765ff108e7c39bf479a1eba201e97ab65cab": container not known 
    at /app/main/resources/app.asar/packages/main/dist/index.js:6:102795
    at c (/app/main/resources/app.asar/packages/main/dist/index.js:6:103126)
    at Vi.buildPayload (/app/main/resources/app.asar/packages/main/dist/index.js:6:102767)
    at IncomingMessage.<anonymous> (/app/main/resources/app.asar/packages/main/dist/index.js:6:102317)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Additional context

![Screenshot from 2022-11-20 14-53-12](https://user-images.githubusercontent.com/19417232/202893679-eeb8d810-1ecd-4da7-aca9-6ac6c7ba67cf.png)

**Comment by tazihad** [comment]
Note: I removed the arch container which has problem by `podman rm arch`. Now it's showing up. I think this is also a bug.

**Comment by Luxvao** [comment]
This happened to me as well. Have you tried to close podman desktop, then stop the podman machine and start it again. If that doesn't work then try to remove the podman machine and init it again.

**Comment by Luxvao** [comment]
[This](https://podman-desktop.io/docs/troubleshooting) may help. There should be a section about not seeing containers if you scroll down.
