### ISSUE TITLE
Podman Desktop binaries are not working

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#8765]
### Bug description

I tried a snapshot and I got an error

```
Uncaught Exception:
TypeError: Class extends value undefined is not a constructor or null
at Object.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/minizlib/dist/commonjs/index.js:138:6)
at Module._compile (node:internal/modules/cjs/loader:1373:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
at Module.load (node:internal/modules/cjs/loader:1215:32)
at Module._load (node:internal/modules/cjs/loader:1031:12)
at c._load (node:electron/js2c/node_init:2:17025)
at Module.require (node:internal/modules/cjs/loader:1240:19)
at require (node:internal/modules/helpers:179:18)
at Object.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/tar/dist/commonjs/parse.js:24:20)
at Module._compile (node:internal/modules/cjs/loader:1373:14)
```

### Operating system

macOS

### Installation Method

None

### Version

next (development version)

**Comment by odockal** [comment]
@benoitf Same on the linux:
```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Yallist is not a constructor
    at LRUCache.reset (/home/odockal/Downloads/podman-desktop-1.13.0-202409041130-aabbbd7/resources/app.asar/node_modules/openid-client/node_modules/lru-cache/index.js:136:22)
    at new LRUCache (/home/odockal/Downloads/podman-desktop-1.13.0-202409041130-aabbbd7/resources/app.asar/node_modules/openid-client/node_modules/lru-cache/index.js:49:10)
    at Object.<anonymous> (/home/odockal/Downloads/podman-desktop-1.13.0-202409041130-aabbbd7/resources/app.asar/node_modules/openid-client/lib/helpers/request.js:62:16)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)

```
I think the problem also shows in the updater e2e test...

**Comment by odockal** [comment]
Issue on the e2e repo, might be related: https://github.com/containers/podman-desktop-e2e/issues/219

**Comment by benoitf** [comment]
it's also working on 13577e14ec4ae24a352df23ae096812d4eeaf026 (when I merged the switch to pnpm)

**Comment by axel7083** [comment]
Do we have an issue open on their side to track the problem ?
