### ISSUE TITLE
e2e-test-main workflow requires to add github token in order to build podman desktop for win-update-e2e-test correctly

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#8808]
### Bug description

Ie.: https://github.com/containers/podman-desktop/actions/runs/10773962330/job/29874913862

Error:
```
Skipping code signing, no environment variables set for that.
Skipping code signing, no environment variables set for that.
  • building block map  blockMapFile=dist\podman-desktop-1.0.0-setup-x64.exe.blockmap
  ⨯ Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
Error: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
    at new GitHubPublisher (D:\a\podman-desktop\podman-desktop\node_modules\app-builder-lib\node_modules\electron-publish\src\gitHubPublisher.ts:52:15)
    at createPublisher (D:\a\podman-desktop\podman-desktop\node_modules\app-builder-lib\src\publish\PublishManager.ts:303:14)
    at PublishManager.getOrCreatePublisher (D:\a\podman-desktop\podman-desktop\node_modules\app-builder-lib\src\publish\PublishManager.ts:222:19)
    at PublishManager.scheduleUpload (D:\a\podman-desktop\podman-desktop\node_modules\app-builder-lib\src\publish\PublishManager.ts:152:28)
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (D:\a\podman-desktop\podman-desktop\node_modules\app-builder-lib\src\publish\PublishManager.ts:202:14)
```

### Operating system

Windows

### Installation Method

Other

### Version

next (development version)

**Comment by odockal** [comment]
Also, e2e test includes update e2e tests on windows. Part of this issue will be fix for running right test on right npm target. `test:e2e:run` is too opened.
