### ISSUE TITLE
podman desktop Initialization start   bug

### ISSUE THREAD

**Issue by zacharydigital** [containers/podman-desktop#8887]
### Bug description

`Error: Command execution failed with exit code 125 Command execution failed with exit code 125 time="2024-09-14T00:30:08+08:00" level=error msg="Error extracting compressed file: \"unexpected EOF\"" Error: unexpected EOF`

### Operating system

Windows 11

### Installation Method

Winget (Windows)

### Version

1.12.0

**Comment by zacharydigital** [comment]
`log : main ↪️ Starting http server to handle webviews on port 44000
log : main ↪️ System ready. Loading extensions...
log : main ↪️ Error while fetching API groups: Error: No active cluster!
error : main ↪️ Refresh of kube resources on startup failed
log : main ↪️ Error while fetching API groups: Error: No active cluster!
error : main ↪️ (node:5192) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'namespace')
    at lme.isContextChanged (C:\Users\zhenx\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:291:5953)
    at lme.update (C:\Users\zhenx\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:291:6752)
    at wx.refresh (C:\Users\zhenx\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:291:30926)
    at async C:\Users\zhenx\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:291:26471
(Use `Podman Desktop --trace-warnings ...` to show where the warning was created)
error : main ↪️ (node:5192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
log : main ↪️ Activating extension (podman-desktop.compose) with max activation time of 20 seconds
warn : MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extensions-started listeners added. Use emitter.setMaxListeners() to increase limit
warn : MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extension-started listeners added. Use emitter.setMaxListeners() to increase limit
warn : MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extension-stopped listeners added. Use emitter.setMaxListeners() to increase limit
log : main ↪️ Activating extension (podman-desktop.compose) ended in 9 milliseconds
log : main ↪️ Activating extension (podman-desktop.docker) with max activation time of 20 seconds
log : main ↪️ Activating extension (podman-desktop.docker) ended in 8 milliseconds
log : main ↪️ Activating extension (podman-desktop.kind) with max activation time of 20 seconds
error : main ↪️ [kind] Error: spawn UNKNOWN
log : main ↪️ PluginSystem: received dom-ready event from the UI
log : main ↪️ Delayed startup, flushing 22 events
log : main ↪️ [kind] kind extension is active
log : main ↪️ Activating extension (podman-desktop.kind) ended in 1187 milliseconds
log : main ↪️ Activating extension (podman-desktop.kube-context) with max activation time of 20 seconds
log : main ↪️ [kube-context] starting extension kube-context
log : main ↪️ [kind] kind extension is active
log : main ↪️ Activating extension (podman-desktop.kube-context) ended in 20 milliseconds
log : main ↪️ Activating extension (podman-desktop.kubectl-cli) with max activation time of 20 seconds
log : main ↪️ Activating extension (podman-desktop.kubectl-cli) ended in 167 milliseconds
log : main ↪️ Activating extension (podman-desktop.lima) with max activation time of 20 seconds
debug : main ↪️ [lima] Could not find socket at C:\Users\zhenx\.lima\podman\sock\podman.sock
log : main ↪️ Activating extension (podman-desktop.lima) ended in 2 milliseconds
log : main ↪️ Activating extension (podman-desktop.podman) with max activation time of 20 seconds
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
log : main ↪️ [kind] kind extension is active
log : main ↪️ [kind] kind extension is active
warn : main ↪️ [podman] Unable to run regex on containers.conf file. Reason: Error: ENOENT: no such file or directory, open 'C:\Users\zhenx\AppData\Roaming\containers\containers.conf'
log : main ↪️ Activating extension (podman-desktop.podman) ended in 198 milliseconds
log : main ↪️ Activating extension (podman-desktop.registries) with max activation time of 20 seconds
log : main ↪️ Activating extension (podman-desktop.registries) ended in 1 milliseconds
log : main ↪️ PluginSystem: initialization done.
log : main ↪️ Autostarting podman-desktop.podman container engine
log : main ↪️ [kind] kind extension is active
error : main ↪️ Error: Unable to fetch the available extensions: Timeout awaiting 'secureConnect' for 2000ms
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 969.0012999999999ms
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 3071.1927000000005ms
error : main ↪️ Error: Unable to fetch the available extensions: Timeout awaiting 'secureConnect' for 2000ms
error : main ↪️ Error: Unable to fetch the available extensions: Timeout awaiting 'response' for 1000ms`

**Comment by danivilla9** [comment]
Hello, we've tried to reproduce the error that you experienced without success. Can you give us more information regarding the initial state of your machine, if there was a previous installation, and the steps to get your result? Even if they seem redundant, it can help us a lot.

**Comment by Supermath101** [comment]
I ran into the same issue, on Windows 11 version `23H2` build `22631.4169`. The installation method I used was the `winget` CLI tool. I "fixed" it by using a custom image when initializing the Podman machine via the Podman Desktop GUI. I downloaded the `5.3-rootfs-amd64.tar.zst` file from [here](https://github.com/containers/podman-machine-wsl-os/releases/latest), extracted the `.tar.zst` file into a `.tar` file, and selected that `5.3-rootfs-amd64.tar` file as the custom image.

I'm not sure if this made any difference, but I also updated Podman to the latest version using the `winget` CLI tool. I don't know why a fresh installation of Podman Desktop would include an out-of-date version of Podman.

**Comment by benoitf** [comment]
FYI 5.3 is not yet released https://github.com/containers/podman/releases
it's the development branch
