### ISSUE TITLE
PD displays incorrect podman machine status and causes race condition in some scenarios

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#8984]
### Bug description

It seems that when PD is used to create a podman machine via onboarding workflows, either using the `Set up` button or the `Initialize and start` button on the dashboard, spinning up the podman machine takes much longer, but after some time the status of the podman machine is displayed in PD as `RUNNING`, however in the podman CLI the podman machine status is still in `Currently starting`, if in this state the user closes the PD app and then reopens it, waits until podman machine is displayed as `RUNNING` again in the app and tries to turn off the podman machine from Settings -> Resources the podman machine will permanently freeze.

https://github.com/user-attachments/assets/df849562-a916-4a91-b5c0-f62186fac499

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

1.12.0

### Steps to reproduce

1. Have no podman machine on the system.
2. Open PD application.
3. Make sure the "Exit on Close" option in settings is enabled.
4. Using the `Set up` or `Initialize and start` buttons create a podman machine with autostart enabled.
5. As soon as the podman machine is shown with status `RUNNING` on the Dashboard, close the PD app.
6. Reopen PD app and wait for podman machine to reach `RUNNING` state on the dashboard.
7. Go into Settings -> Resources and stop the podman machine.
8. Notice that the podman machine will change states from `RUNNING` to `STARTING` and will freeze.

**Comment by feloy** [comment]
When running the steps to reproduce, at step 8, I get these messages in the console (indefinitely):

```
 Engine does not have an API or a libpod API, returning empty array Podman
VM5:62 main ↪️ error is Error: connect ECONNREFUSED /var/folders/d3/0x31crx96g5ftn8cfs3z15jr0000gn/T/podman/podman-machine-default-api.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
VM5:62 main ↪️ Error when handling events Error: Error in handling events
    at Object.callback (/Users/phmartin/Documents/gits/podman-desktop/packages/main/dist/index.cjs:64125:23)
    at /Users/phmartin/Documents/gits/podman-desktop/packages/main/dist/index.cjs:58166:12
    at Modem$1.buildPayload (/Users/phmartin/Documents/gits/podman-desktop/packages/main/dist/index.cjs:54457:20)
    at ClientRequest.<anonymous> (/Users/phmartin/Documents/gits/podman-desktop/packages/main/dist/index.cjs:54441:13)
    at ClientRequest.emit (node:events:519:28)
    at emitErrorEvent (node:_http_client:108:11)
    at Socket.socketErrorListener (node:_http_client:511:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3) Will reconnect in 5s Error: Error in handling events
    at Object.callback (/Users/phmartin/Documents/gits/podman-desktop/packages/main/dist/index.cjs:64125:23)
    at /Users/phmartin/Documents/gits/podman-desktop/packages/main/dist/index.cjs:58166:12
    at Modem$1.buildPayload (/Users/phmartin/Documents/gits/podman-desktop/packages/main/dist/index.cjs:54457:20)
    at ClientRequest.<anonymous> (/Users/phmartin/Documents/gits/podman-desktop/packages/main/dist/index.cjs:54441:13)
    at ClientRequest.emit (node:events:519:28)
    at emitErrorEvent (node:_http_client:108:11)
    at Socket.socketErrorListener (node:_http_client:511:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
```

**Comment by feloy** [comment]
After some tests, I can see that when PD executes the command `podman machine init ...`, if the user exits PD, the podman command is terminated immediately.

This means that at step 5, if the user stops PD before the command `podman machine init` is completely finished, the initialization of the machine can be incomplete and the podman machine can be in an unstable state.

Moreover, when you run the step 4, the `RUNNING` state is displayed before the `podman machine init` is completely finished (about 5 seconds on my mac m3), which makes the previous point easier to satisfy.


https://github.com/user-attachments/assets/152dc334-42e8-451c-ac47-8ddaf17ac326
