### ISSUE TITLE
Clicking on system tray button Version with available update does nothing and throws an error in dev console

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#9378]
### Bug description

Update E2E test is failing when trying to click with mouse cursor on the version button in the status bar with the exclamation mark icon where update is available. Nothing happens and so the test fails. It is suppose to show `Update Available Now` dialog. Instead, an error is thrown in the dev console.

![Image](https://github.com/user-attachments/assets/048a0816-4b0b-4329-8a5f-3698693d91a1)

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.13.0

### Relevant log output
```
An object could not be cloned.
Error: An object could not be cloned.
    at a (file:///D:/a/podman-desktop/podman-desktop/dist/win-unpacked/resources/app.asar/packages/renderer/dist/index-Bo55i8Ic.js:297:32891)
    at HTMLButtonElement.<anonymous> (file:///D:/a/podman-desktop/podman-desktop/dist/win-unpacked/resources/app.asar/packages/renderer/dist/index-Bo55i8Ic.js:297:33423)
    at HTMLButtonElement.s (file:///D:/a/podman-desktop/podman-desktop/dist/win-unpacked/resources/app.asar/packages/renderer/dist/index-Bo55i8Ic.js:2:14538)
```

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/9394
