### ISSUE TITLE
Podman desktop stuck initializing on macOS

### ISSUE THREAD

**Issue by johnmcollier** [containers/podman-desktop#951]
### Bug description

I have Podman 4.3.1 installed on my system (via the macOS install package [here](https://github.com/containers/podman/releases/tag/v4.3.1)). When I download Podman Desktop and run it, it sits at the "Initializing" page and never seems to progress:

<img width="1162" alt="Screen Shot 2022-12-01 at 2 27 08 PM" src="https://user-images.githubusercontent.com/6880023/205142102-4156af6f-99ad-4d76-8639-c33c10dad474.png">

I can confirm that I'm able to use podman just fine via my terminal, and I have a podman machine presently running (`podman machine info` output is pasted below). 

There also doesn't seem to be any noticeable option to see what step(s) it may be stuck or hanging on.

### Operating system

macOS Monterey 12.6.1 (Intel)

### Version

0.10.0

### Steps to reproduce

on macOS:
1. Install Podman 4.3.1
2. Install latest Podman Desktop
3. Start Podman Desktop

### Relevant log output

```shell
I don't see any log output available from Podman Desktop
```

### Additional context

```
johncollier@jcollier-mac ~ % podman machine info
Host:
  Arch: amd64
  CurrentMachine: podman-machine-default
  DefaultMachine: podman-machine-default
  EventsDir: /var/folders/bp/5pzqwrtj79xf5pstx7fk9ybc0000gn/T/podman-run--1/podman
  MachineConfigDir: /Users/johncollier/.config/containers/podman/machine/qemu
  MachineImageDir: /Users/johncollier/.local/share/containers/podman/machine/qemu
  MachineState: Running
  NumberOfMachines: 1
  OS: darwin
  VMType: qemu
Version:
  APIVersion: 4.3.1
  Built: 1668090415
  BuiltTime: Thu Nov 10 09:26:55 2022
  GitCommit: 814b7b003cc630bf6ab188274706c383f9fb9915
  GoVersion: go1.19
  Os: darwin
  OsArch: darwin/amd64
  Version: 4.3.1
```

**Comment by benoitf** [comment]
Hello @johnmcollier are you able to toggle developer tools ( view / toggle developer tools and then 'show console' do you see some errors ?)

**Comment by johnmcollier** [comment]
@benoitf Ah, I saw that option in the menu bar, but I didn't think to check the console output in it 🤦 

```
main ↪️ (node:1862) UnhandledPromiseRejectionWarning: Error: contexts[194].context.cluster is missing
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config_types.js:151:23
    at Object.map (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/underscore/underscore-node-f.cjs:1342:22)
    at newContexts (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config_types.js:131:24)
    at KubeConfig.loadFromString (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:108:56)
    at KubeConfig.loadFromFile (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:77:14)
    at G0.refresh (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.92c0ff7d.js:102:6414)
    at G0.init (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.92c0ff7d.js:102:5451)
    at Q8.initExtensions (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.92c0ff7d.js:127:14905)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.92c0ff7d.js:153:1961
(Use `Podman Desktop --trace-warnings ...` to show where the warning was created)
(anonymous) @ index.ts:921
index.ts:921 main ↪️ (node:1862) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(anonymous) @ index.ts:921
index.ts:921 main ↪️ Error: contexts[194].context.cluster is missing
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config_types.js:151:23
    at Object.map (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/underscore/underscore-node-f.cjs:1342:22)
    at newContexts (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config_types.js:131:24)
    at KubeConfig.loadFromString (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:108:56)
    at KubeConfig.loadFromFile (/Applications/Podman Desktop.app/Contents/Resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:77:14)
    at G0.refresh (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.92c0ff7d.js:102:6414)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.92c0ff7d.js:102:6086
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.92c0ff7d.js:79:19112
    at Z3.invoke (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.92c0ff7d.js:79:19216)
    at zt.fire (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.92c0ff7d.js:81:293)
(anonymous) @ index.ts:921
```

Edit: Also TIL about `Podman Desktop --trace-warnings`

**Comment by benoitf** [comment]
Ok thanks. It seems there is an issue related to the kube config file ( well it shouldn't crash so this is a bug but it might help to debug)

**Comment by johnmcollier** [comment]
@benoitf Yup, removing my current Kube config got it to start 👍

**Comment by johnmcollier** [comment]
For debugging, this seems to be the problematic entry 🙂 :
```
johncollier@jcollier-mac ~ % cat ~/.kube/config-old| yq '.contexts[194]'
context:
  cluster: ""
  user: ""
name: kcp-unstable
```

I don't currently need that in my Kube config, so I'll just remove it for now. And I've also confirmed that removing just that entry gets podman desktop to start

**Comment by benoitf** [comment]
Thanks for the detailed report 🙏

**Comment by benoitf** [comment]
Will be fixed by https://github.com/containers/podman-desktop/pull/953

**Comment by TomasHubelbauer** [comment]
FYI this is still a problem, see #1633.
