### ISSUE TITLE
Error message during Kind cluster deletion

### ISSUE THREAD

**Issue by amisskii** [containers/podman-desktop#9702]
### Bug description

While deleting a Kind cluster through the resources page, a popup error appears. However, after closing the popup, the Kind cluster is successfully deleted.
![Image](https://github.com/user-attachments/assets/f06d5704-bc4f-41a0-aeca-ec760033eb0f)

An error message indicates that there is no active cluster, although the node is in a running state. I can push images and deploy containers to the Kind cluster, and all resources are visible.

UPD: There is a similar error with OpenShift Local (openshift).

### Operating system

Fedora 40

### Installation Method

None

### Version

1.14.0

### Relevant log output

Error

A JavaScript error occurred in the main process

Uncaught Exception:
Error: No active cluster!
at KubeConfig.makeApiClient (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:371:19)
at vc.createServiceInformer (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:293:18133)
at vc.startResourceInformer (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:293:9213)
at update (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:293:11960)
at gve.safeSetState (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:293:4088)
at gve.setStateAndDispatch (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:293:3538)
at Object.onReachable (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:293:11692)
at Timeout._onTimeout (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:293:23910)
at listOnTimeout (node
/timers:581:17)
at process.processTimers (node
/timers:519:7)

**Comment by cbr7** [comment]
Issue also occurs for other cluster types, I was able to reproduce for openshift local and developer sandbox. Seems this is a general issue which happens when the currently selected kubernetes context is deleted by the user.

**Comment by odockal** [comment]
I have the same issue as well, although I see error only in the dev console. There is no nasty popup for me on Mac OS.

**Comment by feloy** [comment]
I can also reproduce by editing the `~/.kube/config` file and removing the `current-context: kind-kind-cluster` file. 
It seems that you need at least 2 contexts to have the error.
