### ISSUE TITLE
Podman Desktop cannot detect WSL2 machine when running on Windows 10 Enterprise LTSC version 21H2 build 19044

### ISSUE THREAD

**Issue by failboat79** [containers/podman-desktop#9809]
### Bug description

This is the last version of Windows 10 that will have LTSC support - it will be present on many industrial systems.

This windows does appear to meet the minimum requirements for the software (and for wsl2) - but getting things working is highly problematic. WSL2 seems to be working fine - I was able to create the podman machine and operate it via the command line. However the Podman Desktop gui cannot connect to this VM at all - the errors in logs are similar to that reported elsewhere when "wsl --version" command fails. 

It seems this system has an old version of the windows components (ie wsl.exe) but the latest version of the wsl kernel. I did run "wsl --update" and it downloaded the new kernel - but this did not fix the issue. Other posts here all suggest that updating windows should fix this problem - but there are no updates for this version of windows.

So I have no success getting the GUI to detect WSL2 machine. But after installing 1.14.1 I tried the new HyperV feature and that seems to work ok. Now am stuck getting compose extension working - but that looks like a self-signed cert problem. 

Is there any known fix for WSL2 on this version of windows? The problem seems to be inside podman desktop rather than WSL. 

### Operating system

Windows 10 Enterprise LTSC build 19044

### Installation Method

Installer from website/GitHub releases

### Version

1.14.0

### Steps to reproduce

Try to install podman desktop with WSL2 support on this version of windows.

### Relevant log output

main ↪️ [podman] unable to check wsl version Error: Command execution failed with exit code 4294967295
main ↪️ Trace: [podman] unable to check wsl version Command execution failed with exit code 4294967295: Command execution failed with exit code 4294967295 at ChildProcess.<anonymous> (C:\Users\xxx\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:344:13023) at ChildProcess.emit (node:events:519:28) at maybeClose (node:internal/child_process:1105:16) at ChildProcess._handle.onexit (node:internal/child_process:305:5) { exitCode: 4294967295, command: 'wsl', stdout: 'Invalid command line option: --version\r\r\n' + 'Copyright (c) Microsoft Corporation. All rights reserved.\r\r\n' + '\r\r\n' + 'Usage: wsl.exe [Argument] [Options...] [CommandLine]\r\r\n' + '\r\r\n' + 'Arguments for running Linux binaries:\r\r\n' + '\r\r\n' + ' If no command line is provided, wsl.exe launches the default shell.\r\r\n' + '\r\r\n' + ' --exec, -e <CommandLine>\r\r\n' + ' Execute the specified command without using the default Linux shell.\r\r\n' + '\r\r\n' + ' --\r\r\n' + ' Pass the remaining command line as is.\r\r\n' + '\r\r\n' + 'Options:\r\r\n' + ' --distribution, -d <Distro>\r\r\n' + ' Run the specified distribution.\r\r\n' + '\r\r\n' + ' --user, -u <UserName>\r\r\n' + ' Run as the specified user.\r\r\n' + '\r\r\n' + 'Arguments for managing Windows Subsystem for Linux:\r\r\n' + '\r\r\n' + ' --help\r\r\n' + ' Display usage information.\r\r\n' + '\r\r\n' + ' --install [Options]\r\r\n' + ' Install additional Windows Subsystem for Linux distributions.\r\r\n' + " For a list of valid distributions, use 'wsl --list --online'.\r\r\n" + '\r\r\n' + ' Options:\r\r\n' + ' --distribution, -d [Argument]\r\r\n' + ' Downloads and installs a distribution by name.\r\r\n' + '\r\r\n' + ' Arguments:\r\r\n' + ' A valid distribution name (not case sensitive).\r\r\n' + '\r\r\n' + ' Examples:\r\r\n' + ' wsl --install -d Ubuntu\r\r\n' + ' wsl --install --distribution Debian\r\r\n' + '\r\r\n' + ' --set-default-version <Version>\r\r\n' + ' Changes the default install version for new distributions.\r\r\n' + '\r\r\n' + ' --shutdown\r\r\n' + ' Immediately terminates all running distributions and the WSL 2\r\r\n' + ' lightweight utility virtual machine.\r\r\n' + '\r\r\n' + ' --status\r\r\n' + ' Show the status of Windows Subsystem for Linux.\r\r\n' + '\r\r\n' + ' --update [Options]\r\r\n' + ' If no options are specified, the WSL 2 kernel will be updated\r\r\n' + ' to the latest version.\r\r\n' + '\r\r\n' + ' Options:\r\r\n' + ' --rollback\r\r\n' + ' Revert to the previous version of the WSL 2 kernel.\r\r\n' + '\r\r\n' + 'Arguments for managing distributions in Windows Subsystem for Linux:\r\r\n' + '\r\r\n' + ' --export <Distro> <FileName>\r\r\n' + ' Exports the distribution to a tar file.\r\r\n' + ' The filename can be - for standard output.\r\r\n' + '\r\r\n' + ' --import <Distro> <InstallLocation> <FileName> [Options]\r\r\n' + ' Imports the specified tar file as a new distribution.\r\r\n' + ' The filename can be - for standard input.\r\r\n' + '\r\r\n' + ' Options:\r\r\n' + ' --version <Version>\r\r\n' + ' Specifies the version to use for the new distribution.\r\r\n' + '\r\r\n' + ' --list, -l [Options]\r\r\n' + ' Lists distributions.\r\r\n' + '\r\r\n' + ' Options:\r\r\n' + ' --all\r\r\n' + ' List all distributions, including distributions that are\r\r\n' + ' currently being installed or uninstalled.\r\r\n' + '\r\r\n' + ' --running\r\r\n' + ' List only distributions that are currently running.\r\r\n' + '\r\r\n' + ' --quiet, -q\r\r\n' + ' Only show distribution names.\r\r\n' + '\r\r\n' + ' --verbose, -v\r\r\n' + ' Show detailed information about all distributions.\r\r\n' + '\r\r\n' + ' --online, -o\r\r\n' + " Displays a list of available distributions for install with 'wsl --install'.\r\r\n" + '\r\r\n' + ' --set-default, -s <Distro>\r\r\n' + ' Sets the distribution as the default.\r\r\n' + '\r\r\n' + ' --set-version <Distro> <Version>\r\r\n' + ' Changes the version of the specified distribution.\r\r\n' + '\r\r\n' + ' --terminate, -t <Distro>\r\r\n' + ' Terminates the specified distribution.\r\r\n' + '\r\r\n' + ' --unregister <Distro>\r\r\n' + ' Unregisters the distribution and deletes the root filesystem.', stderr: '', cancelled: false, killed: false } at C:\Users\xxx\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:349:8767 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by failboat79** [comment]
I was able to get WSL2 working - after manually installing some wsl distribution (like ubuntu 24.04). After that the "wsl --version" commands works as expected, and the gui detects the podman-machine. 

The guide does say to run "wsl --install --no-distribution" - which seems to be a critical initialisation step - but this doesn't work for this version of windows. It seems we have to install something to make it happy. In my case "wsl --install -d ubuntu-24.04". 

This seems to be a trivial hangup - could we just skip this "wsl --version" check altogether? If I run "podman machine init" that works fine - it's only the gui that has a problem. The program is checking for WSL versions on startup - it should not have to do the same check later on.

edit: It seems we can just install ubuntu, then unregister it. Then all is fine! This is an acceptable workaround for this weird version of windows.

**Comment by failboat79** [comment]
After repeating the setup procedure on some other "normal" systems I can point to the exact difference in install procedures.

On a "normal" windows 11 system that has been fully updated and has the features enabled - user must run "wsl --update" and only then will "wsl --install --no-distribution" work. Podman Desktop setup proceeds smoothly then.

On this Windows 10 LTSC system - user must run "wsl --update", but even then "wsl --install --no-distribution" will not work. Instead run "wsl --install -d ubuntu-24.04" (or any other official distro). Let the setup script do its thing, pick a username. Now WSL is in the expected working state and "wsl --version" returns as expected. The ubuntu (or other) we installed can then be removed. Podman Destop setup should work without problems.

**Comment by odockal** [comment]
@shipsing Can you please take a look at this problem? It seems to me we could add that into a troubleshooting section, perhaps?

**Comment by shipsing** [comment]
sure @odockal

**Comment by rujutashinde** [comment]
closing this fixed with #9894

**Comment by odockal** [comment]
@shipsing thanks!
